### ISSUE TITLE
Problem saving pipeline

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#992] opened 2013-12-30 08:26 UTC
experimental branch

I created pipeline with one SPARQL extractor and loader, tried to save. I got: 

![screen shot 2013-12-30 at 9 23 37 am](https://f.cloud.github.com/assets/3014917/1821344/d257f84c-712b-11e3-9abf-c0f55e829f88.png)

java.lang.IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline@319.
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.discoverUnregisteredNewObjects(RepeatableWriteUnitOfWork.java:310) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:723) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1516) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]

**Comment by skodapetr** [comment] 2013-12-30 08:29
It looks like #988, but I will try to fix it anyway

**Comment by skodapetr** [comment] 2013-12-30 08:43
Well I have a theory for exp. branch .. if ODCS try to save the pipeline into database .. and failed .. then then pipeline get's id  .. and then this can happen (as it is not really in database but ODCS this that it is).

Was there any previous exception .. ? smilar like in #991 caused by empty description.

**Comment by tomas-knap** [comment] 2013-12-31 10:35
Yes, the previous exception was #991

**Comment by skodapetr** [comment] 2013-12-31 10:41
Yes, then this is explained .. the ODCS assign id to the pipeline, but failed to save it into database. Then in openEvent application checks that the pipeline has id -> should be in database. And try to use it in relation (save open event) that ends up with this exception.
As the #991 should not happen, I think we can close this for experimental branch.

**Closed as completed** 2013-12-31 10:48 UTC
Labels: bug, priority:high

**Comment by tomas-knap** [comment] 2013-12-31 13:27
Solved
