### ISSUE TITLE
Test GUI in different browsers

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#1187] opened 2014-02-05 22:37 UTC
For @tomesj also, please cooperate.

Play with GUI, look for problems mentioned in #1170. Other problems also.
Write them here or to #1170.
Please provide screenshots and browser with version. Also clear and easy as possible steps to reproduce if possible.
Use latest version or odcs-test instance(mention where the problem occured)

Test in Firefox, IE, Chrome.

**Comment by tomas-knap** [comment] 2014-02-20 15:19
Could be done after 28.2.

**Comment by tomas-knap** [comment] 2014-03-01 17:24
Could you please test that Maria? Write down please version you have used and whether it seems to be working correctly or not. So that we can say to the examiner which browser we support correctly

**Comment by kukharm** [comment] 2014-03-04 04:00
Firefox 27.0.1
1) nekdy dlouho se nacitavali icony statusu a tlacitek
![ff01](https://f.cloud.github.com/assets/3471169/2317486/a07c159c-a34e-11e3-9f4f-6d4fbd736410.jpg)

2) Jednou pri otevreni pipeliny ([INTLIB] Data from psp.cz ) byla zobrazena jen pulka instance,
pak se to neopakovalo
![ff02](https://f.cloud.github.com/assets/3471169/2317491/b94f86ee-a34e-11e3-8be3-03fc8153fc86.jpg)

3) Pri zmenseni (zoom out) kanvasa DPU tree panel je kratka
![ff03](https://f.cloud.github.com/assets/3471169/2317503/23df2dd4-a34f-11e3-9a93-b045128245cb.jpg)

4) BUG! Jsem pridala na kanvas "SPARQL Loader completeness" DPU pak zmacknula Save as DPU template, potom nova dpu se pridala do DPU tree ale DPU tree ztratilo svou strukturu, vsechny DPU se zacali zobrazovat na 1-m levlu. 
![ff04](https://f.cloud.github.com/assets/3471169/2317510/53b6f2e4-a34f-11e3-8de8-baa2109568e0.jpg)
Po opacnem otevreni pipeliny DPU tree uz vypadalo normalne.

5) Kdyz filtruju podle Trace a Debug zobrazujou se take a jine statusy (nevim jestli je to bug nebo spravne chovani)
![ff05](https://f.cloud.github.com/assets/3471169/2317548/f1237c78-a34f-11e3-9c88-8eeb28ed0c59.jpg)

Chrome 33.0.1750.117 m 
problemy 3)-5) jako v FF. V chrome to pracovalo trochu rychlejsi

 IE 8.0.6001.19499
Strasne pomaly, neda se v tom pracovat, jen filtrace trvala mi nekolik sekund. A take:

1) vetrikalni scrollbar
![ie01](https://f.cloud.github.com/assets/3471169/2317580/aea3b92a-a350-11e3-8e4f-02736b2e6b47.jpg)

2) Otevrela jsem DBpediu ale ta se nenacetla v prubehu nekolika minut (stejne s ostatnimi pipelinami)
![ie02](https://f.cloud.github.com/assets/3471169/2317585/c312d13e-a350-11e3-9e8a-bc8693ed5070.jpg)

3) instance tab 
 ![ie03](https://f.cloud.github.com/assets/3471169/2317593/f2848c0a-a350-11e3-933b-88665071a18c.jpg)

Problemy z #1170 u me se neobjavili.

**Comment by tomas-knap** [comment] 2014-03-04 07:35
@bogo777 , tohle si prosim nech na konec a koukni prosim co se da rychle (v radu hodiny, dvou) upravit. Zbytek nechame.

**Comment by tomas-knap** [comment] 2014-03-05 15:01
The most important for Chrome/Firefox is:
-  issue 3)
-  issue 4), which is covered by #1261.

Rest can be future work

**Comment by bogo777** [comment] 2014-03-05 15:01
Firefox,Chrome
1) s tim nic neudelame
2,3) melo by byt vyreseno novou verzi canvasu
4) nedari se mi to zreprodukovat, ani na ODCS
5) to je spravne

IE
- 8 je stara verze, ale ja to obcas poustim v 11 a vypada a chova se to normalne, v 10 by to take melo bezet

**Comment by tomas-knap** [comment] 2014-03-05 15:27
Ok, I will close this, 4) is covered by #1261. Please try to reproduce there

**Closed as completed by tomas-knap** 2014-03-05 15:27 UTC
Labels: bug, priority:normal
