### ISSUE TITLE
Transaction deadlocked when execution monitor record was clicked 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#730] opened 2013-11-04 15:45 UTC
To reproduce on odcs.xrg.cz - try to open last exec monitor record for ares test pipeline. 
Log is in /data/odcs/log/frontend, excerpt:

```
2013-11-04 16:41:44,051 [http-bio-8080-exec-36] DEBUG c.c.m.x.o.f.g.v.executionmonitor.ExecutionMonitor - ExecutionMonitor refreshed.
2013-11-04 16:41:46,984 [http-bio-8080-exec-38] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:41:47,032 [http-bio-8080-exec-36] DEBUG c.c.m.x.o.f.g.v.executionmonitor.ExecutionMonitor - Start of loading of execution detail.
2013-11-04 16:41:50,052 [http-bio-8080-exec-36] DEBUG c.c.m.x.odcs.frontend.gui.tables.LogMessagesTable - Start of reloading the log container
2013-11-04 16:41:51,984 [http-bio-8080-exec-38] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:41:57,059 [http-bio-8080-exec-34] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:41:58,650 [http-bio-8080-exec-36] INFO  org.eclipse.persistence.logging.default - 2013-11-04 16:41:58.646--UnitOfWork(1448525573)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
Error Code: -8
Call: SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))
    bind => [execution, 250, ERROR, FATAL, OFF, WARN, INFO, ALL, DEBUG, TRACE]
Query: ReportQuery(referenceClass=LogMessage sql="SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))").
2013-11-04 16:42:01,983 [http-bio-8080-exec-34] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:03,958 [http-bio-8080-exec-36] INFO  org.eclipse.persistence.logging.default - 2013-11-04 16:42:03.958--UnitOfWork(1448525573)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
Error Code: -8
Call: SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))
    bind => [execution, 250, ERROR, FATAL, OFF, WARN, INFO, ALL, DEBUG, TRACE]
Query: ReportQuery(referenceClass=LogMessage sql="SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))").
2013-11-04 16:42:06,987 [http-bio-8080-exec-34] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:11,982 [http-bio-8080-exec-34] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:14,310 [http-bio-8080-exec-36] INFO  org.eclipse.persistence.logging.default - 2013-11-04 16:42:14.31--UnitOfWork(1448525573)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
Error Code: -8
Call: SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))
    bind => [execution, 250, ERROR, FATAL, OFF, WARN, INFO, ALL, DEBUG, TRACE]
Query: ReportQuery(referenceClass=LogMessage sql="SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))").
2013-11-04 16:42:16,994 [http-bio-8080-exec-31] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:22,030 [http-bio-8080-exec-40] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:26,985 [http-bio-8080-exec-40] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:27,798 [http-bio-8080-exec-36] INFO  org.eclipse.persistence.logging.default - 2013-11-04 16:42:27.798--UnitOfWork(1448525573)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
Error Code: -8
Call: SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))
    bind => [execution, 250, ERROR, FATAL, OFF, WARN, INFO, ALL, DEBUG, TRACE]
Query: ReportQuery(referenceClass=LogMessage sql="SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))").
2013-11-04 16:42:31,982 [http-bio-8080-exec-40] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:36,982 [http-bio-8080-exec-31] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:36,985 [http-bio-8080-exec-31] DEBUG c.c.m.x.o.f.g.v.executionmonitor.ExecutionMonitor - ExecutionMonitor refreshed.
2013-11-04 16:42:37,963 [http-bio-8080-exec-33] DEBUG c.c.m.x.o.f.g.v.executionmonitor.ExecutionMonitor - Start of loading of execution detail.
2013-11-04 16:42:38,154 [http-bio-8080-exec-36] INFO  org.eclipse.persistence.logging.default - 2013-11-04 16:42:38.154--UnitOfWork(1448525573)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
Error Code: -8
Call: SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))
    bind => [execution, 250, ERROR, FATAL, OFF, WARN, INFO, ALL, DEBUG, TRACE]
Query: ReportQuery(referenceClass=LogMessage sql="SELECT COUNT(t0.event_id) FROM logging_event t0, logging_event_property t1 WHERE ((((t1.mapped_key = ?) AND (t1.mapped_value = ?)) AND (t0.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t1.event_id = t0.event_id))").
2013-11-04 16:42:38,161 [http-bio-8080-exec-36] WARN  org.eclipse.persistence.logging.default - 2013-11-04 16:42:38.154--UnitOfWork(1448525573)--
2013-11-04 16:42:38,172 [http-bio-8080-exec-36] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
virtuoso.jdbc4.VirtuosoException: SR172: Transaction deadlocked
    at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoPreparedStatement.executeQuery(Unknown Source) ~[jdbc-driver-4.jar:na]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1007) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:642) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:250) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2737) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllReportQueryRows(ExpressionQueryMechanism.java:2674) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.ReportQuery.executeDatabaseQuery(ReportQuery.java:848) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1127) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:403) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1215) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5529) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5529) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5529) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5529) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1740) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:517) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400) ~[eclipselink-2.5.1-RC1.jar:2.5.1.v20130824-981335c]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:310) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at com.sun.proxy.$Proxy87.getSingleResult(Unknown Source) ~[na:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.IntlibQuery.size(IntlibQuery.java:131) ~[IntlibQuery.class:na]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuery(LazyQueryView.java:407) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuerySize(LazyQueryView.java:392) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.size(LazyQueryView.java:219) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryContainer.size(LazyQueryContainer.java:183) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.tepi.filtertable.paged.PagedFilterTableContainer.getRealSize(PagedFilterTableContainer.java:59) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at org.tepi.filtertable.paged.PagedFilterTable.setPageFirstIndex(PagedFilterTable.java:244) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at org.tepi.filtertable.paged.PagedFilterTable.setCurrentPage(PagedFilterTable.java:309) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at org.tepi.filtertable.FilterFieldGenerator$2.valueChange(FilterFieldGenerator.java:473) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1126) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:542) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:702) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:671) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.AbstractField.setConvertedValue(AbstractField.java:823) ~[vaadin-server-7.1.5.jar:7.1.5]
    at org.tepi.filtertable.FilterTable.setFilterFieldValue(FilterTable.java:245) ~[filteringtable-0.9.0.v7.jar:0.9.0.v7]
    at cz.cuni.mff.xrg.odcs.frontend.gui.tables.LogMessagesTable.setDpu(LogMessagesTable.java:147) ~[LogMessagesTable.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.fillContent(DebuggingView.java:152) ~[DebuggingView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.buildMainLayout(DebuggingView.java:133) ~[DebuggingView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.<init>(DebuggingView.java:63) ~[DebuggingView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionmonitor.ExecutionMonitor.getDebugView(ExecutionMonitor.java:554) ~[ExecutionMonitor.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionmonitor.ExecutionMonitor.buildlogLayout(ExecutionMonitor.java:147) ~[ExecutionMonitor.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionmonitor.ExecutionMonitor.showExecutionDetail(ExecutionMonitor.java:531) ~[ExecutionMonitor.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.views.executionmonitor.ExecutionMonitor.buttonClick(ExecutionMonitor.java:505) ~[ExecutionMonitor.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.5.jar:7.1.5]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.5.jar:7.1.5]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.5.jar:7.1.5]
    at cz.cuni.mff.xrg.odcs.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:52) [IntlibApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2013-11-04 16:42:38,345 [http-bio-8080-exec-36] DEBUG cz.cuni.mff.xrg.odcs.frontend.AppEntry - Backend status refreshed.
2013-11-04 16:42:38,347 [http-bio-8080-exec-36] DEBUG c.c.m.x.o.f.g.v.executionmonitor.ExecutionMonitor - ExecutionMonitor refreshed.
```

**Comment by tomas-knap** [comment] 2013-11-04 15:46
Related to #707 
Try if it can be solved by replaying

**Comment by janvojt** [comment] 2013-11-04 19:19
> To reproduce on odcs.xrg.cz - try to open last exec monitor record for ares test pipeline. 

I cannot reproduce right now. I assume pipeline was running when this happened. This could most likely be prevented by wrapping select queries into read-only transactions. This is happening in the container, so I suggest we postpone until the new container is ready and merged into master.

**Comment by tomas-knap** [comment] 2013-11-06 13:32
Could it be caused by sharing the connection? That means that after opening connection, transaction is started but it is not properly committed after single use?

**Comment by janvojt** [comment] 2013-11-06 13:58
> Communication failure detected when attempting to perform read query outside of a transaction.

If you pay close attention to what the error message actually says, it seems the problem is with a SELECT query run outside of a transaction. So far, I thought that for SELECT queries there is no reason to start a transaction. Apparently, there is. Therefore annotating all facade methods that access database with at least `@Transactional(readonly)` might solve this problem.

As I said, we are refactoring container and facades right now. Therefore I suggest to resolve this after major refactoring is done by making sure all database reads are in a transaction.

**Comment by tomas-knap** [comment] 2013-11-06 14:05
ok

**Comment by tomas-knap** [comment] 2013-11-15 09:26
Please solve that asap when the major refactoring is done, Jakub is asking for that always

**Comment by janvojt** [comment] 2013-11-19 18:47
The new container is using DAO layer, which requires transactions and starts a new one if none is active. DAO implementations always require transactions and throw an exception if none is active (ef5912a8). This will immediately reveal a case where service layer is not managing transactions. Therefore it should work now everywhere except for the old container (IntlibLazyQueryContainer), which is now deprecated.

Issue was reported in ExecutionMonitor. I believe EM is still usign the deprecated container, so it is not yet resolved. Bohuslav is currently refactoring to use MVP model (and the new container), so I am reassining to him.

**Comment by bogo777** [comment] 2013-11-20 09:44
ExecutionList classes are used instead of EM and ILQC is not used there, so this should be resolved?

**Comment by tomas-knap** [comment] 2013-11-21 09:51
So is it solve completely? ILQC is not used anywhere now?

**Comment by janvojt** [comment] 2013-11-21 11:39
OK then, please retest.

**Comment by bogo777** [comment] 2013-11-21 12:30
ILQC is still used in list of pipelines in Schedule pipeline dialog. I tried to replace it with ROC, but it is not possible, combobox requires some operations that are not implemented in ROC and I don't know if it is easy to implement them. I know about indexOfId(Object itemId) but there could be more.

Also RDFLQC is used in Browse/Query.

**Closed as completed** 2013-11-21 15:29 UTC
Labels: bug, priority:high, Test that
