### ISSUE TITLE
Installation: Error when executing schema.sql in Virtuoso 7 Interactive SQL

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#120] opened 2013-07-16 13:52 UTC
SQLState: 42S02
Message: SQ090: Bad table DB.INTLIB.PPL_NODE in trigger delete_node_fix definition

-- workaround for bug in virtuoso's implementation of cascades on delete
-- see https://github.com/openlink/virtuoso-opensource/issues/56
CREATE TRIGGER delete_node_fix BEFORE DELETE ON "DB"."INTLIB"."PPL_NODE" REFERENCING old AS n
{
    DELETE FROM ppl_edge
     WHERE node_from_id = n.id
      OR node_to_id = n.id;
}

**Comment by tomas-knap** [comment] 2013-07-17 15:34
jan, to realize this, you need to test Virtuoso 7 (not 6.1.6 or 6.1.7). Kubo, send to intlib@googlegroups.com please connection string to some testing Virtuoso 7.

**Comment by janvojt** [comment] 2013-07-21 09:07
I cannot reproduce this on given v7.xrg.cz. Seems like table DB.INTLIB.PPL_NODE was not defined when CREATE TRIGGER was issued. Please try again, and if it is OK close this issue.

**Comment by jakubklimek** [comment] 2013-07-23 07:24
I was only successful when using isql to execute the commands. Then, https://github.com/mff-uk/intlib/issues/125 stopped happening, so these are definitely connected. Please provide better error messages :)

**Comment by janvojt** [comment] 2013-07-23 07:45
I can reproduce #125, but not this one. It really seems just a bad copy paste of sql queries. As far as I understand, this happened during import with isql, and I cannot effect error messages of Virtuoso. Moreover, the error message is clear: trigger on table `PPL_NODE` cannot be created, because no such table exists. :)

**Closed as completed by janvojt** 2013-07-23 07:45 UTC
Labels: bug, priority:low
