### ISSUE TITLE
Scheduler access

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#637] opened 2013-10-13 21:41 UTC
I created pipeline by user2 with User role, then i created scheduling rule for this pipeline by the same user. When i try to edit this rule by pressing edit button i get 
![access](https://f.cloud.github.com/assets/3471169/1322841/14e0d51c-3450-11e3-828b-bf5100a3d3cd.png)

**Comment by janvojt** [comment] 2013-11-14 19:35
Duplicate of #756 .

**Closed as completed by janvojt** 2013-11-14 19:35 UTC
Labels: bug, duplicate, priority:high
