### ISSUE TITLE
DPU - replace authentication

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#415] opened 2013-09-07 17:25 UTC
I get "An authen.. object was not found" when I try to replace DPU. 
Step to reproduce:
DPU Templates
select DPU click "Repalce"
select file .. and wait

There probably will be another (but different) exception as the original bundle is not properly uninstalled .. 

necessary for #249

**Comment by janvojt** [comment] 2013-09-07 20:01
The problem is, that authentication context is kept in a ThreadLocal. Vaadin's component Upload has a succeed listener which seems to run on a different thread than the HTTP request. I will do some more debugging. Please disable the security annotations for now, so you can work on your issue.

**Comment by jakubklimek** [comment] 2013-09-09 09:44
Still geting that - or is it a different one?
![image](https://f.cloud.github.com/assets/718827/1105898/5432d580-1934-11e3-8c1a-a16c06d12cf5.png)

**Comment by janvojt** [comment] 2013-09-09 09:59
It is the same exception, but caused by a different line. I know where the problem is. I will fix this tonight. I could not retest the whole scenario myself, because at the time there was a different bug causing BundleException.

**Comment by janvojt** [comment] 2013-09-09 20:40
Please retest. I am not 100% sure it works, because right now even the version before the last commit works on my setup.

**Comment by jakubklimek** [comment] 2013-09-10 09:29
Still does not work. I am bumping the priority, becasue when this problem occurs on the server, it means deleting all pipelines, the DPU, then uploading a new version and recreating the pipelines instead of the replace.

Btw, you can test it on the current live instance on <a href="http://odcs.xrg.cz:8080/odcleanstore">http://odcs.xrg.cz:8080/odcleanstore</a>. It is the version before your commit, but I tested it on my current version and it still does it.

![image](https://f.cloud.github.com/assets/718827/1113390/9c1d3e86-19fb-11e3-8ab8-123aed91d86a.png)

**Comment by janvojt** [comment] 2013-09-10 21:19
Should be fixed now. There is only one cosmetic problem - DPU file label does not refresh after upload. You can click a different DPU and then back to see the change.
I am assigning Bohuslav to resolve this.

**Comment by jakubklimek** [comment] 2013-09-11 05:49
Another cosmetic problem to fix is that the Template Configuration tab is not updated after the replace

**Comment by jakubklimek** [comment] 2013-09-11 09:19
An I found a functional problem too. I replaced the DPU, hit F5, clicked on the replaced DPU and got this:
![image](https://f.cloud.github.com/assets/718827/1121515/415d2e34-1ac3-11e3-8871-b997ea29de4e.png)

**Comment by janvojt** [comment] 2013-09-11 17:13
This has nothing to do with DPU replace. It is a general problem as I found. I created a new issue #464 for that problem.

**Closed as completed by janvojt** 2013-09-11 17:13 UTC
Labels: bug, priority:high
