### ISSUE TITLE
Starting of tomcat app - questions:

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#591] opened 2013-10-05 09:19 UTC
1. What is the EL Warning caused by? What is its consequence?
2. Why is the JDBC Driver Connection create 5 times?

```
11:16:13.121 [localhost-startStop-2] INFO  v.ConfigurableDataSource - Loaded JDBC driver: virtuoso.jdbc4.Driver
[EL Warning]: metadata: 2013-10-05 11:16:13.959--ServerSession(2106190519)--You have specified multiple ids for the entity class [cz.cuni.mff.xrg.odcs.commons.app.execution.log.LogExceptionLine] without specifying an @IdClass. By doing this you may lose the ability to find by identity, distributed cache support etc. Note: You may however use entity manager find operations by passing a list of primary key fields. Else, you will have to use JPQL queries to read your entities. For other id options see @PrimaryKey.
11:16:14.286 [localhost-startStop-2] INFO  c.c.m.x.o.c.a.m.o.OSGIModuleFacadeConfig - com.vaadin version: 7.1.5
11:16:15.256 [localhost-startStop-2] INFO  c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading libraries from: /Users/tomasknap/Documents/PROJECTS/ETL-SWProj/intlib/target/lib
11:16:15.257 [localhost-startStop-2] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /Users/tomasknap/Documents/PROJECTS/ETL-SWProj/intlib/target/lib/commons-module-1.0.0.jar
11:16:15.387 [localhost-startStop-2] DEBUG v.ConfigurableDataSource - Creating new JDBC DriverManager Connection to [jdbc:virtuoso://localhost:1111/charset=UTF-8]
11:16:15.416 [localhost-startStop-2] DEBUG v.ConfigurableDataSource - Creating new JDBC DriverManager Connection to [jdbc:virtuoso://localhost:1111/charset=UTF-8]
11:16:16.005 [localhost-startStop-2] DEBUG v.ConfigurableDataSource - Creating new JDBC DriverManager Connection to [jdbc:virtuoso://localhost:1111/charset=UTF-8]
11:16:16.026 [localhost-startStop-2] DEBUG v.ConfigurableDataSource - Creating new JDBC DriverManager Connection to [jdbc:virtuoso://localhost:1111/charset=UTF-8]
11:16:16.032 [localhost-startStop-2] DEBUG v.ConfigurableDataSource - Creating new JDBC DriverManager Connection to [jdbc:virtuoso://localhost:1111/charset=UTF-8]
11:16:16.036 [localhost-startStop-2] DEBUG v.ConfigurableDataSource - Creating new JDBC DriverManager Connection to [jdbc:virtuoso://localhost:1111/charset=UTF-8]
11:16:16.040 [localhost-startStop-2] DEBUG v.ConfigurableDataSource - Creating new JDBC DriverManager Connection to [jdbc:virtuoso://localhost:1111/charset=UTF-8]
11:16:16.045 [localhost-startStop-2] DEBUG v.ConfigurableDataSource - Creating new JDBC DriverManager Connection to [jdbc:virtuoso://localhost:1111/charset=UTF-8]
11:16:16.051 [localhost-startStop-2] DEBUG c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Installing bundle from 'RDF_extractor'/'RDF_extractor-1.0.0.jar'
11:16:16.
```

**Comment by bogo777** [comment] 2013-10-05 10:53
Warning is caused by LogExceptionLine, which is class from @janvojt, so I am reassigning him. 
I think JDBC DriverManager Connection are created plenty in whole app.(For each transaction maybe?)

**Comment by janvojt** [comment] 2013-10-05 11:08
1. I think it is clear from the message detail.
   - it is caused by composite primary key
   - consequence is also stated in the message, but it has no implications for our use cases (we only access LogExceptionLine through LogException#getLines())
2. This is expected for current implementation. A smarter way of using connections would be setting up connection pooling.

If you have no further questions, please close the issue.

**Comment by tomas-knap** [comment] 2013-10-05 13:32
Honzo, please document that in the code (in the comment of ConfigurableDataSource) and than close this issue.

**Closed as completed** 2013-10-09 08:34 UTC
Labels: priority:high, needsDiscussion
