### ISSUE TITLE
Virtuoso 7 - Issue when running dbpedia pipeline for the first time on Windows with backend and frontend running

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#125] opened 2013-07-16 15:19 UTC
```
Exception in thread "Thread-4" javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: Bad column number : 0 not in 1<n<17
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1295)
    at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:876)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
    at com.sun.proxy.$Proxy30.merge(Unknown Source)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade.save(PipelineFacade.java:153)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$FastClassByCGLIB$$13bb3988.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$53b14186.save(<generated>)
    at cz.cuni.xrg.intlib.backend.execution.Engine.run(Engine.java:112)
    at cz.cuni.xrg.intlib.backend.execution.Engine.checkDatabase(Engine.java:129)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onEvent(Engine.java:194)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onApplicationEvent(Engine.java:212)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onApplicationEvent(Engine.java:1)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324)
    at cz.cuni.xrg.intlib.backend.Heartbeat.run(Heartbeat.java:42)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.exception.SQLGrammarException: Bad column number : 0 not in 1<n<17
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:122)
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractResultSetProxyHandler.continueInvocation(AbstractResultSetProxyHandler.java:108)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
    at com.sun.proxy.$Proxy36.getLong(Unknown Source)
    at org.hibernate.type.descriptor.sql.BigIntTypeDescriptor$2.doExtract(BigIntTypeDescriptor.java:66)
    at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:65)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:269)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:265)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:238)
    at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:357)
    at org.hibernate.loader.Loader.extractKeysFromResultSet(Loader.java:702)
    at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:635)
    at org.hibernate.loader.Loader.doQuery(Loader.java:856)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
    at org.hibernate.loader.Loader.loadEntity(Loader.java:2058)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)
    at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697)
    at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439)
    at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420)
    at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)
    at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
    at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
    at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)
    at org.hibernate.internal.SessionImpl.get(SessionImpl.java:870)
    at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:460)
    at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:256)
    at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:86)
    at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:781)
    at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:766)
    at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:770)
    at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:867)
    ... 24 more
Caused by: virtuoso.jdbc4.VirtuosoException: Bad column number : 0 not in 1<n<17
    at virtuoso.jdbc4.VirtuosoRow.getLong(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getLong(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getLong(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractResultSetProxyHandler.continueInvocation(AbstractResultSetProxyHandler.java:104)
    ... 55 more
```

**Comment by tomas-knap** [comment] 2013-07-17 06:28
Jan, can you find something interesting from the log above? Or more info needed.

**Comment by jakubklimek** [comment] 2013-07-17 06:31
I forgot to mention that ODCS is configured to use the localRDF store and the Virtuoso used as RDB is not on localhost.

**Comment by jakubklimek** [comment] 2013-07-19 08:36
Now this happend without even running a pipeline. I just ran backend, did nothing and this exception popped out:

```
Exception in thread "Thread-4" javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: Bad column number : 0 not in 1<n<17
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1295)
    at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:876)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
    at com.sun.proxy.$Proxy30.merge(Unknown Source)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade.save(PipelineFacade.java:153)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$FastClassByCGLIB$$13bb3988.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.xrg.intlib.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$778e5e61.save(<generated>)
    at cz.cuni.xrg.intlib.backend.execution.Engine.run(Engine.java:112)
    at cz.cuni.xrg.intlib.backend.execution.Engine.checkDatabase(Engine.java:129)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onEvent(Engine.java:194)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onApplicationEvent(Engine.java:212)
    at cz.cuni.xrg.intlib.backend.execution.Engine.onApplicationEvent(Engine.java:1)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324)
    at cz.cuni.xrg.intlib.backend.Heartbeat.run(Heartbeat.java:42)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.exception.SQLGrammarException: Bad column number : 0 not in 1<n<17
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:122)
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractResultSetProxyHandler.continueInvocation(AbstractResultSetProxyHandler.java:108)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
    at com.sun.proxy.$Proxy36.getLong(Unknown Source)
    at org.hibernate.type.descriptor.sql.BigIntTypeDescriptor$2.doExtract(BigIntTypeDescriptor.java:66)
    at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:65)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:269)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:265)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:238)
    at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:357)
    at org.hibernate.loader.Loader.extractKeysFromResultSet(Loader.java:702)
    at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:635)
    at org.hibernate.loader.Loader.doQuery(Loader.java:856)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
    at org.hibernate.loader.Loader.loadEntity(Loader.java:2058)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)
    at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697)
    at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439)
    at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420)
    at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)
    at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
    at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
    at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)
    at org.hibernate.internal.SessionImpl.get(SessionImpl.java:870)
    at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:460)
    at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:256)
    at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:86)
    at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:781)
    at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:766)
    at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:770)
    at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:867)
    ... 24 more
Caused by: virtuoso.jdbc4.VirtuosoException: Bad column number : 0 not in 1<n<17
    at virtuoso.jdbc4.VirtuosoRow.getLong(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getLong(Unknown Source)
    at virtuoso.jdbc4.VirtuosoResultSet.getLong(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.hibernate.engine.jdbc.internal.proxy.AbstractResultSetProxyHandler.continueInvocation(AbstractResultSetProxyHandler.java:104)
    ... 55 more
```

**Comment by tomas-knap** [comment] 2013-07-19 19:27
Honza, please check this. If you need more info to the bug, just write.

**Comment by janvojt** [comment] 2013-07-20 16:27
The stacktrace looks pretty generic. Column number 0 makes no sense (to me). I tried running backend with localRdf config, works OK. I doubt it has something to do with remote host, because even on localhost data is send through TCP. I cannot test on Windows, because I only have linux boxes. However, all other developers use Windows, so I assume they would encounter this. Please provide more details:
1. Is this 100% reproducible? If so provide steps how to reproduce.
2. Does it happen with localRdf only, or with virtuoso as well?
3. Does it happen on Windows only, or is it platform independent?
4. Which commit was this simulated on?

Please recreate database before testing.

**Comment by jakubklimek** [comment] 2013-07-21 08:12
1. Yes (on my machine). Just run backend and wait a minute.
2. Both – It is Virtuoso 7, maybe that is the problem?
3. Don’t know, only have Windows
4. Simulated on https://github.com/mff-uk/intlib/commit/48d32e0dcebeb86b5193e206c86d20e3c81760f4

JK

**Comment by janvojt** [comment] 2013-07-21 08:30
My guess is Virtuoso 7. You are probably the first one to test it on version 7. Also, issue #120 may be relevant here. I don't have Virtuoso 7 installed, it would be great if you emailed me the login to the server you are connecting to, if it is public. This was already requested by @tomas-knap, but I never received such email.

**Comment by janvojt** [comment] 2013-07-23 07:40
I can reproduce this on v7.xrg.cz. The error does not tell me much, so far I have no idea where the problem is. Will research further.

**Comment by janvojt** [comment] 2013-12-21 09:57
This is very old. Exception is thrown in hibernate, which we are not using anymore (we use eclipselink instead). I tested Virtuoso 7 this week and did not experience this. I am closing.

**Closed as completed by janvojt** 2013-12-21 09:57 UTC
Labels: bug, priority:normal
