### ISSUE TITLE
Big log refresh slow

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#625] opened 2013-10-11 15:01 UTC
When log has > 10000 pages, its refresh still gets slow even though it should not.

**Comment by janvojt** [comment] 2013-10-12 18:13
If this was simulated before 1b049ea8, it is most likely resolved by this commit.

**Comment by tomas-knap** [comment] 2013-10-13 08:12
No, it was simulated after that commit

**Comment by tomas-knap** [comment] 2013-10-13 08:15
The problem is that the refreshing of pipeline execution is still slower and slower as the number of logs is increasing (during the pipeline execution). Because of the lazy query container and fixed-sized log view, this should not happen. I would suggest to check the model of the log view, if e.g. the previously generated logs are not held as the pipeline is being executed?

**Comment by bogo777** [comment] 2013-10-14 08:41
I think it is because of keeping execution and DPU as property in other table. When loading data, it fetches these properties for each log.

My log is full of these queries:

```
[EL Fine]: sql: 2013-10-14 10:37:01.026--ServerSession(791687840)--Connection(1026982922)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [1 parameter bound]
[EL Fine]: sql: 2013-10-14 10:37:01.027--ServerSession(791687840)--Connection(44422464)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [1 parameter bound]
[EL Fine]: sql: 2013-10-14 10:37:01.028--ServerSession(791687840)--Connection(1413966432)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [1 parameter bound]
[EL Fine]: sql: 2013-10-14 10:37:01.029--ServerSession(791687840)--Connection(2091573216)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [1 parameter bound]
[EL Fine]: sql: 2013-10-14 10:37:01.03--ServerSession(791687840)--Connection(1228637426)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [1 parameter bound]
[EL Fine]: sql: 2013-10-14 10:37:01.031--ServerSession(791687840)--Connection(957676971)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [1 parameter bound]
[EL Fine]: sql: 2013-10-14 10:37:01.032--ServerSession(791687840)--Connection(1118811409)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [1 parameter bound]
[EL Fine]: sql: 2013-10-14 10:37:01.032--ServerSession(791687840)--Connection(191554075)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [1 parameter bound]
```

I don't know, why JOIN in not used, I think that it should help.

**Comment by bogo777** [comment] 2013-10-14 09:03
Actually, the first query looks good:

```
SELECT TOP 8792,8820 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
```

But it's only beginning of very long series of queries in the last comment. I have over 6200 of them, and about 15 000 logs in db total.

**Comment by tomas-knap** [comment] 2013-10-14 09:16
Mno, ano, tohle posledni query vypada ok, ale nechapu k cemu jsou pak jeste ty dalsi dotazy, kdyz by stacil ten jeden? Bohuslav, povis to Honzovi, jestli by nekouknul proc Hibernate generuje ty zbytecne dotazy? Jeste ke vsemu to vypada, ze ty queries sql: 2013-10-14 10:37:01.031--ServerSession(791687840)--Connection(957676971)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?) se provadi pro kazdy jeden log zvlast?

**Comment by tomas-knap** [comment] 2013-10-14 11:00
Honzo, can you please tune the querying, so that the extra queries sql: 2013-10-14 10:37:01.031--ServerSession(791687840)--Connection(957676971)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?) se neprovadi? Imho nic neprinasi.

**Comment by janvojt** [comment] 2013-10-15 11:07
I think the problem is that IntlibLazyQueryContainer loads only a single entity, in this case LogMessage. The query for fetching LogMessage is joined with properties, to apply DPU/Execution filter. That is why you see LogMessage correctly joined with properties in the first query. However this join is done purely for the purpose of filtering. Container does not know about the existence of this join, and so cannot benefit from it by loading the properties from the same result. As one may notice, query 

```
SELECT TOP 8792,8820 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
```

does not even select anything from table `t0`, only `t1`. Therefore the query is also wrong.

The solution would be to implement a new feature into new IntlibLazyQueryContainer. Along with the entity class passed to constructor we could also pass attribute names which we want to be preloaded. This would be a nicer solution, but might be quite complicated.

A different solution as Bohuslav says would be to introduce new columns into table logging_event and setup a trigger for updating it. This would be a quick fix, but we might run into the same problem with a different entity.

Which way do we want to go? I suggest we try the trigger and extra columns (we were already considering this for different reasons). Then if we have time we can implement extra functionality with preload hints into LazyQueryContainer.

**Comment by tomas-knap** [comment] 2013-10-15 12:21
Well, and what about implementing our own DAO methods for getting the list of log message/dpu events which are new from the last update? This should be pretty straightforward (updating a bit the query above). 

What exactly happens when the log viewer is to be refreshed? How is the intlibLazyQuery container populated with new data?

**Comment by tomas-knap** [comment] 2013-10-15 13:03
In the IntlibQuery, the queries for the filters has to be constructed. So what is the problem to construct manually query for getting the list of log message/dpu events which are new from the last update?

**Comment by tomas-knap** [comment] 2013-10-17 19:09
I am just launching ares test pipeline. I launch the pipeline in debug and watch the debug detail - I have to wait for 5-7seconds for new data. During that time, vaading is loading data and gui is not responding, i cannot click on anything

**Comment by tomas-knap** [comment] 2013-10-17 19:10
Honza, could you please check the queries which are being executed during updating log records?

**Comment by tomas-knap** [comment] 2013-10-17 19:10
sorry, bych nejdriv mohl zkusit posledni verzi :D

**Comment by tomas-knap** [comment] 2013-10-18 07:05
Tak zkousim posledni verzi, zatim mam logy na prvni strance a poustim to v normal modu. Nacteni 10ti log recordu trva nejake 2-3 vteriny. To neni unosne :( Zkontrolujes Honzo prosim ty dotazy, co se tam generuji?

**Comment by bogo777** [comment] 2013-10-18 07:32
Jeste na tom pracuji, ale uz v te aktualni verzi by melo byt to nacitani dat v jinem vlakne, tudiz to samotne nahrani novych dat by melo byt rychle. U me to je vzdy do vteriny...

**Comment by tomas-knap** [comment] 2013-10-18 11:19
Parada, to uz funguje dobre. Narazil jsem akorat na jeden problem a to, ze mi to obcas ukazuje logy pro jinou pipeline. 

To reproduce. I have one pipeline already finished, the second still running. As I am switching in the execution monitor between these two records, sometimes it happens that it is shows logs for a different pipeline that it is highlighted:

![screen shot 2013-10-18 at 1 15 29 pm](https://f.cloud.github.com/assets/3014917/1359798/160379aa-37e7-11e3-8c24-14846cc36925.png)

(showing logs fro ARES when dbpedia pipeline is highlighted)

**Comment by tomas-knap** [comment] 2013-10-18 11:23
When I open debug view as the pipeline is launched and I am checking new logs for that pipeline, everything is smooth. But when I click firstly on the execution record in the monitor for the execution already running and having generated certain logs, the firs open of log viewer tooks 7s+. But this is not needed, because again only the couple of last logs is visible to the user.

**Comment by tomas-knap** [comment] 2013-10-18 11:33
Bohuslav, please check  that even for the first opening of Log browser, only the needed logs are loaded

**Comment by bogo777** [comment] 2013-10-18 14:47
I fixed problem with showing logs from different pipeline. For the long loading 7s+ I have no solution yet. It happened to me too, but I cannot reproduce it on demand, so it will take some time.

In new version of log table, execution id filter is set to container before it is assigned to table, so there should not be any unneccessary data loaded.

I inspected the log from when long load happened to me, and there weren't any suspicious queries.

**Comment by bogo777** [comment] 2013-10-22 15:03
I investigated this and found out, that the queries to db are sometimes slow. I'm pasting some of the queries from browsing logs:

EL Fine]: sql: 2013-10-22 16:51:45.054--ServerSession(1887951298)--Connection(1380507825)--SELECT TOP 48916,9 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
    bind => [execution, 287, ERROR, FATAL, OFF, INFO, WARN, ALL, DEBUG, TRACE]
[EL Fine]: sql: 2013-10-22 16:52:01.655--ServerSession(1887951298)--Connection(1735639180)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)

[EL Fine]: sql: 2013-10-22 16:53:15.334--ServerSession(1887951298)--Connection(1705810579)--SELECT TOP 48888,28 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
    bind => [execution, 287, ERROR, FATAL, OFF, INFO, WARN, ALL, DEBUG, TRACE]
[EL Fine]: sql: 2013-10-22 16:53:21.087--ServerSession(1887951298)--Connection(1187287321)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [261684]

[EL Fine]: sql: 2013-10-22 16:54:08.95--ServerSession(1887951298)--Connection(1689603813)--SELECT TOP 48832,28 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
    bind => [execution, 287, ERROR, FATAL, OFF, INFO, WARN, ALL, DEBUG, TRACE]
[EL Fine]: sql: 2013-10-22 16:54:11.743--ServerSession(1887951298)--Connection(859594481)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [261628]

[EL Fine]: sql: 2013-10-22 16:54:40.908--ServerSession(1887951298)--Connection(529023888)--SELECT TOP 27972,28 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
    bind => [execution, 287, ERROR, FATAL, OFF, INFO, WARN, ALL, DEBUG, TRACE]
[EL Fine]: sql: 2013-10-22 16:54:42.751--ServerSession(1887951298)--Connection(219941208)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [240768]

[EL Fine]: sql: 2013-10-22 16:55:20.518--ServerSession(1887951298)--Connection(1646483912)--SELECT TOP 3332,28 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
    bind => [execution, 287, ERROR, FATAL, OFF, INFO, WARN, ALL, DEBUG, TRACE]
[EL Fine]: sql: 2013-10-22 16:55:20.861--ServerSession(1887951298)--Connection(2142732491)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [216128]

[EL Fine]: sql: 2013-10-22 16:56:12.591--ServerSession(1887951298)--Connection(815722328)--SELECT TOP 41972,28 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
    bind => [execution, 287, ERROR, FATAL, OFF, INFO, WARN, ALL, DEBUG, TRACE]
[EL Fine]: sql: 2013-10-22 16:56:13.551--ServerSession(1887951298)--Connection(1640923102)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [254768]

[EL Fine]: sql: 2013-10-22 16:57:17.839--ServerSession(1887951298)--Connection(193640847)--SELECT TOP 46340,28 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id))
    bind => [execution, 287, ERROR, FATAL, OFF, INFO, WARN, ALL, DEBUG, TRACE]
[EL Fine]: sql: 2013-10-22 16:57:20.586--ServerSession(1887951298)--Connection(1521597967)--SELECT t0.mapped_value, t0.mapped_key FROM logging_event_property t0 WHERE (t0.event_id = ?)
    bind => [259136]

The 2 queries are part of the same loading of log page and are the second is immediately after the first. I don't know, why it takes such long time. Sometimes it is considerably faster, there is no rule to this.

**Comment by janvojt** [comment] 2013-10-22 21:44
Maybe the reason is simply that your disk/CPU is busy servicing other applications (maybe backend?)? I did not run into this problem on my PC, load times are always the same.

**Comment by bogo777** [comment] 2013-10-23 07:39
Does same means that they are fast? There is also problem with speed on http://odcs.xrg.cz/ 
So is it possible, that such query takes seconds? Also it depends on total number of logs -> for DbPedia pipeline it takes just a moment, but for 1000+ pages of logs, it takes 5s+

**Comment by tomas-knap** [comment] 2013-10-23 09:22
Well, on fresh install, showing logs for dbpedia is immediate. So it takes longer because of bigger log table.

**Comment by tomas-knap** [comment] 2013-10-23 09:23
How many queries are executed for each loading of logs (last page?)? Just one query? Or for each record?

**Comment by bogo777** [comment] 2013-10-23 15:00
One query for page of logs, and then queries to fetch the properties for each log. But those are fast.

**Comment by tomas-knap** [comment] 2013-10-24 09:14
So the first query is slow which obtains the records from log_event table? In my case it is slow everytime whenever I click on some pipeline. 

What about rewritting the slow query? Or adjusting the db schema? I do not understand why the query: SELECT TOP 46340,28 t1.event_id AS a1, t1.level_string AS a2, t1.formatted_message AS a3, t1.logger_name AS a4, t1.thread_name AS a5, t1.timestmp AS a6 FROM logging_event_property t0, logging_event t1 WHERE ((((t0.mapped_key = ?) AND (t0.mapped_value = ?)) AND (t1.level_string IN (?, ?, ?, ?, ?, ?, ?, ?))) AND (t0.event_id = t1.event_id)) can take 5-7s

**Comment by tomas-knap** [comment] 2013-10-25 09:10
This is associated with the findings in #209, which should be solved as part of #702. Yes?

**Comment by janvojt** [comment] 2013-10-25 09:31
Yes.

**Comment by tomas-knap** [comment] 2013-11-01 09:31
New container should solve this issue. Please prepare container for Execution monitor and write findings.

**Comment by tomas-knap** [comment] 2013-11-15 09:37
Check that it is solved by the new container

**Comment by tomas-knap** [comment] 2013-11-22 14:33
1 log table 
pruning - promaznuti logu na zaklade prop v config.properties 
asociace

**Comment by skodapetr** [comment] 2013-11-29 18:20
Nove je pridano take davkove pridavani logu do databaze, tedy je treba nasadit na ODCS a otestovat za realneho rezimu.

**Comment by tomas-knap** [comment] 2013-12-02 15:48
It works fine

**Closed as completed by tomas-knap** 2013-12-02 15:48 UTC
Labels: bug, priority:high, Test that
