### ISSUE TITLE
Error when DPU finishes

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#629] opened 2013-10-11 15:46 UTC
<pre><code>2013-10-11 17:42:09,374 [Thread-124] INFO  exec:10143 dpu:32 c.c.m.x.o.b.dpu.event.DPUEvent - DPU 'PSP.CZ' finished
[EL Warning]: 2013-10-11 17:42:09.462--UnitOfWork(1325259832)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR197: Non unique primary key on DB.INTLIB.EXEC_RECORD.
Error Code: -8
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
        bind => [7 parameters bound]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@7f072fad)
Exception in thread "Thread-124" org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR197: Non unique primary key on DB.INTLIB.EXEC_RECORD.
Error Code: -8
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
        bind => [7 parameters bound]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@7f072fad)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
        at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUFacade$$EnhancerByCGLIB$$f36e1834.save(<generated>)
        at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onDPUEvent(EventListenerDatabase.java:29)
        at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onApplicationEvent(EventListenerDatabase.java:45)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324)
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:398)
        at java.lang.Thread.run(Thread.java:724)
Caused by: javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR197: Non unique primary key on DB.INTLIB.EXEC_RECORD.
Error Code: -8
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
        bind => [7 parameters bound]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@7f072fad)
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:157)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512)
        ... 13 more
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: SR197: Non unique primary key on DB.INTLIB.EXEC_RECORD.
Error Code: -8
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
        bind => [7 parameters bound]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@7f072fad)
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1611)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:962)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:631)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:377)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489)
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80)
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301)
        at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1726)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:226)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:125)
        at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4196)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1531)
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169)
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132)
        ... 14 more
Caused by: virtuoso.jdbc4.VirtuosoException: SR197: Non unique primary key on DB.INTLIB.EXEC_RECORD.
        at virtuoso.jdbc4.VirtuosoResultSet.process_result(Unknown Source)
        at virtuoso.jdbc4.VirtuosoResultSet.getMoreResults(Unknown Source)
        at virtuoso.jdbc4.VirtuosoPreparedStatement.sendQuery(Unknown Source)
        at virtuoso.jdbc4.VirtuosoPreparedStatement.executeUpdate(Unknown Source)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890)
        ... 45 more
2013-10-11 17:42:09,643 [Thread-141] DEBUG exec:10143 dpu:1010 c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Installing bundle from 'SPARQL_transformer'/'SPARQL_transformer-1.0.0.jar'
2013-10-11 17:42:09,669 [Thread-141] DEBUG exec:10143 dpu:1010 c.c.m.x.o.b.c.DataUnitMerger - renaming: output -> input
2013-10-11 17:42:09,672 [Thread-141] DEBUG exec:10143 dpu:1010 c.c.m.x.o.b.c.DataUnitMerger - creating new dataUnit: output
2013-10-11 17:42:09,675 [Thread-141] INFO  exec:10143 dpu:1010 c.c.m.x.o.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/10143/dpu/1010/du/0
2013-10-11 17:42:09,678 [Thread-141] INFO  exec:10143 dpu:1010 c.c.m.x.o.r.i.VirtuosoRDFRepo - Virtuoso repository with data graph <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/10143/dpu/1010/du/0> successfully incicialized.
2013-10-11 17:42:13,069 [Thread-141] INFO  exec:10143 dpu:1010 c.c.m.x.o.r.i.VirtuosoRDFRepo - START merging 414436 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/10143/dpu/32/du/0> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/10143/dpu/1010/du/0>.
</code></pre>

**Comment by janvojt** [comment] 2013-10-12 18:01
The error message is quite clear. The problem is in your database. We use sequences for generating IDs. It seems like the sequence is generating ID that is already in the table.

You should resolve by setting sequence to a higher value with `sequence_set('seq_exec_record', X, 1);`, where X is the result of following query:

```
SELECT MAX(id)+1 FROM exec_record;
```

Please close this issue if this resolves your problem.

**Comment by tomas-knap** [comment] 2013-10-13 08:23
I set the sequence to higher value

**Comment by tomas-knap** [comment] 2013-10-13 10:31
Ok, so this problem is caused by database being suddenly inrespondable, which causes that sequence is not properly updated? See #634

**Comment by janvojt** [comment] 2013-10-15 10:35
> Ok, so this problem is caused by database being suddenly inrespondable, which causes that sequence is not properly updated? See #634

I don't think so. Sequence is incremented before its value is retrieved.

**Comment by tomas-knap** [comment] 2013-10-18 13:37
Duplicates #635

**Closed as completed by tomas-knap** 2013-10-18 13:37 UTC
Labels: bug, priority:urgent
