### ISSUE TITLE
Double exception when replacing DPUs

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#480] opened 2013-09-13 11:32 UTC
In the version of ODCS currently deployed on the server, I get two exceptions at once when replacing my DPU with a newer version

![image](https://f.cloud.github.com/assets/718827/1137843/15525f02-1c68-11e3-8100-f35a7e319406.png)

**Comment by skodapetr** [comment] 2013-09-13 14:27
The problem is in the way in which frontned's "replace" code works. The source of this exception is when the new file has new name. Then the file with the new name is loaded .. the path is updated .. and then the file is probably deleted. It is not my code .. so I have to do some research first and then I can try to fix this.

**Comment by bogo777** [comment] 2013-09-14 10:07
I glanced at the code and it would also need some research for me, reassigning Maria as she is author of original code.

**Comment by skodapetr** [comment] 2013-09-14 17:40
I reassign to me. Actually I have already found bug in replace code and a several "features" that can cause trouble in the future. As I discuss with Thomas replace is not top priority task. I fix the bug and "features" and take care about the whole replace thing myself.

**Closed as completed** 2013-09-24 16:21 UTC
Labels: bug, priority:normal
