### ISSUE TITLE
NPE when debugging from canvas.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#1153] opened 2014-01-31 18:05 UTC
Reproduce on same scenario as in #1104, but looks like it happens everytime.

![screenshot from 2014-01-31 19 03 59](https://f.cloud.github.com/assets/2247062/2053111/3bdec82e-8aa2-11e3-9d93-f60a25245cce.png)

Stacktrace:

```
java.lang.NullPointerException: null
        at com.vaadin.data.util.filter.Compare.equals(Compare.java:312) ~[vaadin-server-7.1.10.jar:7.1.10]
        at org.tepi.filtertable.FilterFieldGenerator$2.valueChange(FilterFieldGenerator.java:471) ~[filteringtable-0.9.3.v7.jar:0.9.3.v7]
        at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1127) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.ui.AbstractField.setValue(AbstractField.java:542) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:702) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:671) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.ui.AbstractSelect.removeAllItems(AbstractSelect.java:829) ~[vaadin-server-7.1.10.jar:7.1.10]
        at cz.cuni.mff.xrg.odcs.frontend.gui.tables.LogTable.refreshDpuSelector(LogTable.java:171) ~[LogTable.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.tables.LogTable.refresh(LogTable.java:260) ~[LogTable.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.fillContent(DebuggingView.java:267) ~[DebuggingView.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.refresh(DebuggingView.java:294) ~[DebuggingView.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.RefreshManager$1.refresh(RefreshManager.java:71) ~[RefreshManager$1.class:na]
        at com.github.wolfie.refresher.Refresher.fireRefreshEvents(Refresher.java:72) ~[refresher-1.2.1.7.jar:1.2.1.7]
        at com.github.wolfie.refresher.Refresher.access$1(Refresher.java:70) ~[refresher-1.2.1.7.jar:1.2.1.7]
        at com.github.wolfie.refresher.Refresher$1.refresh(Refresher.java:35) ~[refresher-1.2.1.7.jar:1.2.1.7]
        at sun.reflect.GeneratedMethodAccessor246.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1382) [vaadin-server-7.1.10.jar:7.1.10]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.10.jar:7.1.10]
        at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:67) [ODCSApplicationServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.37]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.37]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.37]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.37]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.37]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.37]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) [catalina.jar:7.0.37]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.37]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.37]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.37]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.37]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.37]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
```

**Comment by skodapetr** [comment] 2014-01-31 18:08
The source of the problem may be same as in #1126, #1101

**Comment by bogo777** [comment] 2014-02-03 15:50
I updated addon to latest version, this problem was mentioned as fixed in the change log, so please retest it, I can't reproduce this locally.

**Comment by janvojt** [comment] 2014-02-03 16:26
OK, thx, I will retest tomorrow. I am assigning myself so I do not forget about it.

**Closed as completed** 2014-02-04 16:49 UTC
Labels: bug, priority:urgent, Test that
