### ISSUE TITLE
Filter using calendar component is not working property

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#135] opened 2013-07-18 09:05 UTC
![screen shot 2013-07-18 at 11 03 06 am](https://f.cloud.github.com/assets/3014917/818103/ff487306-ef88-11e2-8888-fe74237485c3.png)

THe data in the calendar cannot be set, if selected only "From". If only from is selected, thus the user would like to receive events from one day to now. This has to work. Similarly, if only "To" is selected, user would like to see events from the past till the defined date. THis works for table with logs, but NOT for table with events and pipeline executions. 

If TO is earlier than FROM, a warning should occur and the data cannot be set.

**Comment by bogo777** [comment] 2013-07-18 13:01
I found the source of the problem in discussion forum for FilteringTable addon.

https://vaadin.com/old-forum/-/message_boards/view_message/1168867#_19_message_3353074

It works fine in table with log messages, LogMessage class date is saved as Long in db, and date is created in getter.

In other cases, dates are saved as Date with `@Temporal(javax.persistence.TemporalType.TIMESTAMP)` annotation, which I think is causing the trouble.

I tried, but failed to change the type to Timestamp and I do not know, if it is the right way to go.

So I am reassigning this issue to Honza, who has better understanding of db.

**Closed as completed** 2013-07-23 20:37 UTC
Labels: bug, priority:normal

**Comment by janvojt** [comment] 2013-07-23 20:55
I believe this is a bug in Vaadin's method `com.vaadin.data.util.filter.Compare#compareValue`. The problem is in the following snippet:

``` java
protected int compareValue(Object value1) {
    if (null == value) {
        return null == value1 ? 0 : -1;
    } else if (null == value1) {
        return 1;
    } else if (getValue() instanceof Comparable
            // PROBLEM!!!
            && value1.getClass().isAssignableFrom(getValue().getClass())) { 
        return -((Comparable) getValue()).compareTo(value1);
    }
    throw new IllegalArgumentException("Could not compare the arguments: "
            + value1 + ", " + getValue());
}
```

I believe instead it should be as follows:

``` java
protected int compareValue(Object value1) {
    if (null == value) {
        return null == value1 ? 0 : -1;
    } else if (null == value1) {
        return 1;
    } else if (getValue() instanceof Comparable
            // PROBLEM FIXED
            && Comparable.class.isAssignableFrom(getValue().getClass())) {
        return -((Comparable) getValue()).compareTo(value1);
    }
    throw new IllegalArgumentException("Could not compare the arguments: "
            + value1 + ", " + getValue());
}
```

It seems the later is intended. `value` is checked to allow casting it to `value1`, but it is actually casted to `Comparable` instead. In our case `value1` is read from DB, so its type is `java.sql.Timestamp extends java.util.Date`, `value` is provided by `FilteringTable` addon and typed `Date`. Obviously, superclass cannot be casted to subclass, so exception is thrown even though in our case both objects are perfectly comparable (both implement `Comparable`).

I resolved by setting the column in table to `Timestamp` and commented appropriately.
