### ISSUE TITLE
NPE - filter.Compare.equals()

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1101] opened 2014-01-23 16:58 UTC
When debugging a pipeline on odcs test, I got: 

![screen shot 2014-01-23 at 5 56 09 pm](https://f.cloud.github.com/assets/3014917/1986690/573bf870-844f-11e3-9b14-4fc690f4993d.png)

2014-01-23 17:56:36,237 [http-bio-8080-exec-740] TRACE c.c.m.x.odcs.frontend.gui.components.DebuggingView - Tables refresh start
2014-01-23 17:56:36,242 [http-bio-8080-exec-740] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at com.vaadin.data.util.filter.Compare.equals(Compare.java:312) ~[vaadin-server-7.1.10.jar:7.1.10]
    at org.tepi.filtertable.FilterFieldGenerator$2.valueChange(FilterFieldGenerator.java:471) ~[filteringtable-0.9.3.v7.jar:0.9.3.v7]
    at sun.reflect.GeneratedMethodAccessor3677.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1127) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:542) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:702) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:671) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.ui.AbstractSelect.removeAllItems(AbstractSelect.java:829) ~[vaadin-server-7.1.10.jar:7.1.10]
    at cz.cuni.mff.xrg.odcs.frontend.gui.tables.LogTable.refreshDpuSelector(LogTable.java:197) ~[LogTable.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.tables.LogTable.refresh(LogTable.java:286) ~[LogTable.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.fillContent(DebuggingView.java:240) ~[DebuggingView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.DebuggingView.refresh(DebuggingView.java:267) ~[DebuggingView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.RefreshManager$1.refresh(RefreshManager.java:71) ~[RefreshManager$1.class:na]
    at com.github.wolfie.refresher.Refresher.fireRefreshEvents(Refresher.java:72) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at com.github.wolfie.refresher.Refresher.access$1(Refresher.java:70) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at com.github.wolfie.refresher.Refresher$1.refresh(Refresher.java:35) ~[refresher-1.2.1.7.jar:1.2.1.7]
    at sun.reflect.GeneratedMethodAccessor3675.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1382) [vaadin-server-7.1.10.jar:7.1.10]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.10.jar:7.1.10]
    at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:67) [ODCSApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
2014-01-23 17:56:41,220 [http-bio-8080-exec-740] DEBUG org.eclipse.persistence.logging.sql - 2014-01-23 17:56:41.22--ServerSession(127677047)--Connection(1409205414)--SELECT TOP 0,1 ID AS a1, opened AS a2, user_id AS a3, pipeline_id AS a4 FROM ppl_open_event WHERE ((user_id = ?) AND (pipeline_id = ?))
    bind => [1, 168]

**Comment by skodapetr** [comment] 2014-01-25 09:42
Info: It looks like the problem appears when user selects some dpu in log's filter and then select the empty filter. It does not happen when switching the filter between different dpus.

**Comment by skodapetr** [comment] 2014-01-25 10:15
Also it looks like we have the exactly same problem for more the one drop down boxe in frontend (just try the ExecutionList filter by Status .. ) 
@bogo777 , @tomas-knap do we have some Vaadin update? or do you have any idea why this can be? 

The exception I talk about has different trace .. also as can be seen from the stack trace .. there is not a method from us.

```
java.lang.NullPointerException: null
    at com.vaadin.data.util.filter.Compare.equals(Compare.java:312) ~[vaadin-server-7.1.8.jar:7.1.8]
    at org.tepi.filtertable.FilterFieldGenerator$2.valueChange(FilterFieldGenerator.java:471) ~[filteringtable-0.9.3.v7.jar:0.9.3.v7]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1126) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:542) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:702) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.ComboBox.changeVariables(ComboBox.java:664) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:396) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:221) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:67) [ODCSApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.42]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.42]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.42]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.42]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.42]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.42]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023) [tomcat-coyote.jar:7.0.42]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.42]
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852) [tomcat-coyote.jar:7.0.42]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
    at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
```

**Comment by bogo777** [comment] 2014-01-25 10:37
I updated Vaadin and FilteringTable addon to latest version in 30ef34e88a42a9111f51a687a436eee855fca8ba

Can we confirm that it is caused by that?

**Comment by skodapetr** [comment] 2014-01-25 10:53
We can switch to version before-after and try to replicate this.

**Comment by bogo777** [comment] 2014-01-25 12:29
Vaadin version in pom.xml was strange. I think I fixed it in 3ca2a18a87307cb54ec33fb57d7cbedc55b3acdb
Could be related/solved the problem.

**Comment by tomas-knap** [comment] 2014-01-30 12:03
To reproduce (another case):
- exec monitor ,select status, deselect status.

**Comment by tomas-knap** [comment] 2014-01-30 12:09
Vypada to, ze je chyba v addonu, viz: http://tepi.virtuallypreinstalled.com/filteringtable-v7/?restartApplication

Pouzit starsi verzi?

**Comment by tomas-knap** [comment] 2014-01-30 12:09
Nebo jiny addon?

**Comment by tomas-knap** [comment] 2014-01-31 11:35
Tohle prosim zkus vyresit, jinak si uzivatel rekne, ze nam to haze hodne chyba a pritom za to muze addon. Nejlepe asi tim testem startsi verze

**Comment by bogo777** [comment] 2014-02-03 15:50
I updated addon to latest version, this problem was mentioned as fixed in the change log, so please retest it, I can't reproduce this locally.

**Closed as completed** 2014-02-05 09:45 UTC
Labels: bug, priority:urgent, Test that
