### ISSUE TITLE
Authentication: session times out often, sometimes producing weird errors

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#410] opened 2013-09-07 11:36 UTC
I was in DPUTemplates page for a long time, then I clicked create template, uploaded file and when clicking Save, I got this: (which is apparently caused by session timeout):
![image](https://f.cloud.github.com/assets/718827/1101200/a6152cb0-17b1-11e3-96c2-d6849d95744b.png)

However, I noticed that the login session is probably too short, often I need to relogin, that should be more persistent.

Even worse, I was editing a pipeline and when I clicked on Save, I got:
![image](https://f.cloud.github.com/assets/718827/1101263/762c6fca-17b8-11e3-9da4-68faa6618f8e.png)

**Comment by jakubklimek** [comment] 2013-09-07 12:26
May be related to https://github.com/mff-uk/intlib/issues/411

**Comment by janvojt** [comment] 2013-09-07 20:07
The first screen is a duplicate of #415, where it is discussed.

**Comment by janvojt** [comment] 2013-09-08 14:27
The second screen - I can confirm that authentication is lost after few minutes. I debugged this, and it seems the session lasts 30 minutes which is default and is correct. The problem is that session attribute gets lost somewhere. It might be caused by a PUSH handler, where FakeHttpSession is used. I need to do some more research.

**Closed as completed** 2013-09-12 14:51 UTC
Labels: bug, priority:high
