### ISSUE TITLE
When ODCS is already running and another instance is started, it ends with an exception

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#373] opened 2013-09-05 08:05 UTC

**Comment by tomas-knap** [comment] 2013-09-05 08:46
Petre, could you please adjust that, so that it does not ends with exception, but just writes "Could not start because another instance is running" and stops? SO that it looks like a standard behavior, not like an exception.

**Comment by skodapetr** [comment] 2013-09-05 15:30
Yes I can .. but it come up wit question about logging .. as for further use we can need to see detail of some exception.

Like we should normally log into file (so user can provide us with this information in order to fix something).. and use std::in,out to communicate with user, don't we? And then .. we can give user nice a readable messages .. for example:  "We are sorry .. but the communication port is already in use .. don't you have other Intlib instance already up and running?"

Similar situation is with Frontend as for example "Uncaught exception" does maybe provide some nice way how to inform user that something goes wrong (not so nice as it could .. ) but if user experience such behaviour, I'm no able to help him based on screen-shot as the information shown somehow useless. (ref. to the google's discussion group)

**Comment by skodapetr** [comment] 2013-09-05 20:29
Tomas please test, is that what you have want backend to do?

**Comment by tomas-knap** [comment] 2013-09-06 12:57
Petre, 

in case of error/warning, there should be one line of message saying that there was some problem and then detailed information (even stack trace) can be logged at the debug level. In the productive environment, when the bugs are tuned, we can switch debug level off.

**Comment by tomas-knap** [comment] 2013-09-06 12:58
Sorry for not explaining it properly from the beginning ;)

**Comment by jakubklimek** [comment] 2013-09-13 08:39
<pre><code> - Can't start TCP/IP server
10:36:17 [main] DEBUG c.c.x.i.backend.AppEntry - 
cz.cuni.xrg.intlib.commons.app.communication.CommunicationException: java.net.BindException: Address already in use: JVM_Bind
    at cz.cuni.xrg.intlib.backend.communication.Server.init(Server.java:96) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.AppEntry.initNetworkServer(AppEntry.java:129) [classes/:na]
    at cz.cuni.xrg.intlib.backend.AppEntry.run(AppEntry.java:175) [classes/:na]
    at cz.cuni.xrg.intlib.backend.AppEntry.main(AppEntry.java:228) [classes/:na]
Caused by: java.net.BindException: Address already in use: JVM_Bind
    at java.net.DualStackPlainSocketImpl.bind0(Native Method) ~[na:1.7.0_25]
    at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source) ~[na:1.7.0_25]
    at java.net.AbstractPlainSocketImpl.bind(Unknown Source) ~[na:1.7.0_25]
    at java.net.PlainSocketImpl.bind(Unknown Source) ~[na:1.7.0_25]
    at java.net.ServerSocket.bind(Unknown Source) ~[na:1.7.0_25]
    at java.net.ServerSocket.<init>(Unknown Source) ~[na:1.7.0_25]
    at java.net.ServerSocket.<init>(Unknown Source) ~[na:1.7.0_25]
    at cz.cuni.xrg.intlib.backend.communication.Server.init(Server.java:89) ~[classes/:na]
    ... 3 common frames omitted
10:36:17 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Stopping OSGI framework ...
10:36:17 [main] INFO  c.c.x.i.backend.AppEntry - Closing application ...</code></pre>

**Comment by skodapetr** [comment] 2013-09-13 12:14
And what is the expected behaviour? As I understand it it should enable running two instances with different config.file and prevent when running two instances of the same config file?

**Comment by jakubklimek** [comment] 2013-09-13 12:17
Well, it should interpret the stack trace somehow. This looks like a crash. It is the same situation as before. Before, it crashed because the port was open. The solution was to say that the port is open and don't show the trace. That was fixed, but now it is back again.

**Comment by skodapetr** [comment] 2013-09-13 12:23
Yes, we discuss this with Thomas and he decide that the error will be logged as error and the stack trace as debug .. so for release we disable the debug for sdt::out and there will be no stack trace for this. But I can do an exception in this case and remove the stack trace completely.

**Comment by jakubklimek** [comment] 2013-09-13 12:26
In this case there was ONLY the stack trace, no explanation.

**Comment by skodapetr** [comment] 2013-09-13 14:17
Backend now should prevent running two instances on the same port ..  I hope this could resolve the problem in more "professional" way then updating the log messages.

**Comment by jakubklimek** [comment] 2013-09-15 10:18
Now it ends with <code>Fail to set application lock</code>. That still does not explain what happened and what can be done about it.

**Comment by skodapetr** [comment] 2013-09-21 08:52
Based on our skype discussion I consider this issues to be solved. Closing.

**Closed as completed by skodapetr** 2013-09-21 08:52 UTC
Labels: bug, priority:normal
