### ISSUE TITLE
Possibility to cancel the pipeline execution

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#100] opened 2013-07-12 12:43 UTC
There should be button "cancel", which allows to stop and cancel the pipeline execution.

**Comment by tomas-knap** [comment] 2013-07-29 13:39
This seems to be very important. If I launch a complex pipeline but realize some errors, I should be able to stop the pipeline. 

Currently, I have to stop backend, and if I would like to prevent the pipeline from being reexecuted, I have to manually set its state to e.g. wrong. 

Solution: Button Cancel in pipeline execution monitor  to cancel the pipeline execution. When pressing the button, the given DPU should be killed immediately, all the generated graphs should be cleared.

**Comment by jakubklimek** [comment] 2013-08-21 07:04
Also, when a pipeline is in a SCHEDULED state, I should be able to "pause" it and "resume" it. For example, when a pipeline is running and I stop the backend, when I run it again, it is again scheduled and starts to run. Currently there is no way to "pause" it.

**Comment by tomas-knap** [comment] 2013-08-21 07:11
We were discussing that but postponed possibility to pause/resume, see #262

**Comment by tomas-knap** [comment] 2013-08-26 09:15
Melo by jit o okamzity cancel. Tedy ze by se zabilo bezici DPUcko a pipeline byla ve stavu cancelled. Asi by bylo fajn aby DPU mohl implementovat metodu, diky ktere po sobe v techto pripadech uklidi.

**Comment by tomas-knap** [comment] 2013-08-28 16:08
Petre, k tomu zabijeni pipelines, kazda pipeline bezi ve vlastnim vlakne v PipelineWorkeru, ne?
Tedy slo by to udelat tak, ze kdyz by uzivatel stiskl tlacitko cancel, tak by se poslal signal vlaknu, aby se prerusilo -  to lze metodou interrupt(). Nasledne staci odchytavat v PipelineWorkeru InterruptedException (urcite v metode run, ale take v metode runNode vzdy u prislusneho pousteni DPUcka, kde je mozne nasledne na prerusenem DPU zavolat nejakou metodu cancelled() - to je metoda, ktera je v nejakem rozhrani DPUcka a kterou muze DPU developer definovat, cimz po sobe uklidi.

**Comment by skodapetr** [comment] 2013-08-31 12:41
The pipeline can be cancelled now even during DPU execution. But there is no cleanUp method yet but the registered (input-output) DataUnits are released. 
We can probably add new pipeline execution state like "CANCELLING"? Also I was unable to update frontend so the "stop" button become disabled once pipeline "stop" flag is on.

**Comment by tomas-knap** [comment] 2013-09-01 16:39
Petre, yes, we should have probably two new states: cancelling (which appears when the cancel/stop button is pressed) and cancelled (when the pipeline is cancelled, stopped and method cleanUp finished. What do you think?

"Also I was unable to update frontend so the "stop" button become disabled once pipeline "stop" flag is on." Do not understand where the problem is?

**Comment by jakubklimek** [comment] 2013-09-02 07:28
Does not work correctly. When I clicked Stop, it interrupted the currently running DPU in the pipeline (ended with exception - not sure if this is OK), but not the pipeline itself. The pipeline was in the "running" state and connected DPUs started to run as if the interrrupted DPU finished normally. The whole time the Stop button was still clickable and I ame not sure what would happen if I clicked it again. Finally, the pipeline finished but its final state was FAILED.

Log:

<pre><code>IX 02, 2013 9:03:48 DOP. cz.cuni.xrg.intlib.commons.app.conf.AppConfig <init>
INFO: Loading configuration from: C:\Users\Kuba/.intlib/config.properties
SLF4J: The following loggers will not work because they were created
SLF4J: during the default configuration phase of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: virtuoso.ConfigurableDataSource
IX 02, 2013 9:03:50 DOP. cz.cuni.xrg.intlib.commons.app.conf.AppConfig <init>
INFO: Loading configuration from: C:\Users\Kuba/.intlib/config.properties
09:03:50 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
09:03:55 [main] INFO  c.c.x.i.backend.AppEntry - Configuring dynamic module worker ...
09:03:55 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Starting module facade
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading libs from C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\com.springsource.javax.servlet-2.4.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\commons-web-0.0.1.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\jsoup-1.6.3.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-client-compiled-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-server-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-shared-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-shared-deps-1.0.2.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-theme-compiler-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-themes-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading libs from C:\Users\Kuba\Documents\GitHub\intlib\target\lib
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\commons-module-0.0.1.jar'
09:03:56 [main] INFO  c.c.x.i.b.execution.Engine - Configuring engine ...
09:03:56 [main] INFO  c.c.x.i.b.execution.Engine - Working dir: C:\Users\Kuba\Documents\GitHub\intlib\backend\working
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - Starting TCP/IP server ...
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - Heartbeat is running ... 
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - DPURecord directory: C:\Users\Kuba\Documents\GitHub\intlib\target\
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - Listening on port: 5010
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - Running ...
09:08:51 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - Started
09:08:52 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:08:52 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/0
09:08:52 [Thread-5] INFO  c.c.x.i.b.e.d.i.AnnotationProcessor - Create output DataUnit for field: contractsDataUnit
09:08:52 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:08:53 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/1
09:08:53 [Thread-5] INFO  c.c.x.i.b.e.d.i.AnnotationProcessor - Create output DataUnit for field: profilesDataUnit
09:11:54 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloading URL (attempt 0): ezak.olivius.cz/profile_display_97.html/XMLdataVZ?od=01012013&do=31122013
09:12:05 [Thread-5] INFO  c.c.x.i.c.e.Extract - Timeout (attempt 0) in 10414 : ezak.olivius.cz/profile_display_97.html/XMLdataVZ?od=01012013&do=31122013
09:12:05 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloading URL (attempt 0): www.vestnikverejnychzakazek.cz/Views/Form/Display/347454
09:12:06 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloaded URL (attempt 0) in 740 ms : www.vestnikverejnychzakazek.cz/Views/Form/Display/347454
09:12:06 [Thread-5] DEBUG c.c.x.i.c.e.Extract - 1
09:12:06 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloading URL (attempt 0): ghlucin.profilzadavatele.cz/XMLdataVZ?od=01012013&do=31122013
09:12:06 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Sleeping: 1825
09:12:08 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloaded URL (attempt 0) in 2011 ms : ghlucin.profilzadavatele.cz/XMLdataVZ?od=01012013&do=31122013
09:12:08 [Thread-5] DEBUG c.c.x.i.c.e.Extract - 2
09:12:08 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloading URL (attempt 0): www.vestnikverejnychzakazek.cz/Views/Form/Display/347462
09:12:08 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Sleeping: 1920
09:12:10 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloaded URL (attempt 0) in 2558 ms : www.vestnikverejnychzakazek.cz/Views/Form/Display/347462
09:12:10 [Thread-5] DEBUG c.c.x.i.c.e.Extract - 3
09:12:11 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloading URL (attempt 0): www.profilzadavatele.cz/profil-zadavatele/obec-baska_333/XMLdataVZ?od=01012013&do=31122013
09:12:11 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Sleeping: 1790
09:12:13 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloaded URL (attempt 0) in 1962 ms : www.profilzadavatele.cz/profil-zadavatele/obec-baska_333/XMLdataVZ?od=01012013&do=31122013
09:12:13 [Thread-5] DEBUG c.c.x.i.c.e.Extract - 4
09:12:13 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloading URL (attempt 0): www.vestnikverejnychzakazek.cz/Views/Form/Display/347333
09:12:13 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Sleeping: 1930
...
09:19:08 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Downloading URL (attempt 0): www.vestnikverejnychzakazek.cz/Views/Form/Display/346209
09:19:08 [Thread-5] DEBUG c.c.x.i.c.e.Extract - Sleeping: 1871
09:19:08 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - Terminating the DPU thread ...
java.lang.InterruptedException: sleep interrupted
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Processed in 614763ms
    at java.lang.Thread.sleep(Native Method)
    at cz.cuni.mff.css_parser.utils.Cache.getDocument(Cache.java:140)
    at cz.mff.cuni.scraper.lib.template.ScrapingTemplate.parse(ScrapingTemplate.java:65)
    at cz.opendata.linked.buyer_profiles.Extractor.extract(Extractor.java:112)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executeInstance(Executor.java:271)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:396)
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:425)
    at java.lang.Thread.run(Unknown Source)
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Rows: 6140
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Cancelled rows: 0
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Warnings: 14
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Errors: 42
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Missing ICOs on profile details: 141
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Missing ICOs in profile XML: 0
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Invalid XML: 605 (5%)
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Profiles: 12232
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Zakázky: 26358
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Uchazeči: 43050
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Dodavatelé: 15244
09:19:08 [Thread-5] INFO  c.c.x.i.c.e.Extract - Subdodavatelé: 1090
09:19:09 [Thread-5] INFO  c.c.x.i.c.e.Extract - Více dodavatelů u jedné zakázky: 1023
09:19:09 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:19:09 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/2
09:19:09 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:19:09 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/3
09:19:09 [Thread-5] DEBUG o.o.rio.RDFParserRegistry - Registered service class org.openrdf.rio.binary.BinaryRDFParserFactory
09:19:09 [Thread-5] DEBUG o.o.rio.RDFParserRegistry - Registered service class org.openrdf.rio.n3.N3ParserFactory
09:19:09 [Thread-5] DEBUG o.o.rio.RDFParserRegistry - Registered service class org.openrdf.rio.ntriples.NTriplesParserFactory
09:19:09 [Thread-5] DEBUG o.o.rio.RDFParserRegistry - Registered service class org.openrdf.rio.rdfxml.RDFXMLParserFactory
09:19:09 [Thread-5] DEBUG o.o.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trig.TriGParserFactory
09:19:09 [Thread-5] DEBUG o.o.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trix.TriXParserFactory
09:19:09 [Thread-5] DEBUG o.o.rio.RDFParserRegistry - Registered service class org.openrdf.rio.turtle.TurtleParserFactory
09:19:09 [Thread-5] DEBUG o.o.rio.RDFParserRegistry - Registered service class org.openrdf.rio.nquads.NQuadsParserFactory
09:23:33 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - DPU thread terminated
09:23:33 [Thread-7] INFO  c.c.x.i.b.c.DataUnitMerger - renaming: contracts -> input
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/3/du/0
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 0 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/0> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/3/du/0>.
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/3/du/1
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 0 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/1> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/3/du/1>.
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:23:33 [Thread-7] INFO  c.c.x.i.b.c.DataUnitMerger - renaming: contracts -> input
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/3/du/2
09:23:33 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 514575 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/2> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/3/du/2>.
09:23:51 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:23:51 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:23:51 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/3/du/3
09:23:51 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 411827 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/3> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/3/du/3>.
09:24:05 [Thread-7] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:24:05 [Thread-7] INFO  c.c.x.i.b.e.d.i.AnnotationProcessor - Assign DataUnit names: input for field: rdfDataUnit
09:24:07 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:24:07 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/0
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 0 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/0> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/0>.
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:24:08 [Thread-9] INFO  c.c.x.i.b.c.DataUnitMerger - renaming: profiles -> input
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/1
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 0 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/1> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/1>.
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/2
09:24:08 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 514575 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/2> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/2>.
09:24:25 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:24:25 [Thread-9] INFO  c.c.x.i.b.c.DataUnitMerger - renaming: profiles -> input
09:24:25 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:24:25 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/3
09:24:25 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 411827 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/3> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/3>.
09:24:40 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:24:40 [Thread-9] INFO  c.c.x.i.b.e.d.i.AnnotationProcessor - Assign DataUnit names: input for field: rdfDataUnit
09:24:43 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - Execution failed
09:24:44 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - Clean up
09:24:44 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:24:44 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:24:44 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:24:44 [Thread-11] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:08 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:08 [Thread-12] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:15 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:15 [Thread-13] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:15 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:15 [Thread-14] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:15 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:15 [Thread-15] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:23 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:23 [Thread-16] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:29 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:29 [Thread-17] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:29 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:29 [Thread-18] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:29 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:29 [Thread-19] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:35 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:35 [Thread-20] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:38 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:38 [Thread-21] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
</code></pre>

**Comment by tomas-knap** [comment] 2013-09-02 12:11
So based on our discussion:
- Petre pls check that the rest of the pipeline is not executed when dpu is cancelled
- Add cleanUp method call, default void implementation of cleanUp to the Base class of DPUs

**Comment by tomas-knap** [comment] 2013-09-05 09:47
Jirka, please test that

**Comment by jakubklimek** [comment] 2013-09-08 17:07
I tried stopping again. My DPU catches the Interrupted exception and should end. However, this exception is now not thrown when I click cancel. In the log I see <code>19:04:03 [pool-2-thread-2] DEBUG c.c.x.i.b.e.p.Executor - Terminating the DPU thread ...</code> and the DPU continues (And the button should be Stop, not cancel)

**Comment by tomas-knap** [comment] 2013-09-09 08:41
Kubo, which DPU was it, so that it can be reroduced?

**Comment by jakubklimek** [comment] 2013-09-09 09:07
This is the buyer-profiles DPU. Yes, it can be reproduced. Just run it and try to stop it.

I can provide you with its <a href="http://opendata.cz/files/Extractor_buyer_profiles_cz-0.0.1.jar.zip">cache</a> (approx 130MB zip) so that it does not download anything. I suspect that the cancelling works when the DPU sleeps - it throws the InterruptedException. But when the DPU has everything cached and therefore does not download anything and does not sleep, cancelling does nothing.

DPU usage: set "only last year":true, "override cache": false, "accessprofiles": true

**Comment by tomas-knap** [comment] 2013-09-10 14:52
Many uses of stop should be replaced by code that simply modifies some variable to indicate that the target thread should stop running. The target thread should check this variable regularly, and return from its run method in an orderly fashion if the variable indicates that it is to stop running.

Implement method which may be called regularly by DPU

**Comment by jakubklimek** [comment] 2013-09-11 14:39
Also, keep in mind that we want to see 2 states of the pipeline.

1) when cancel is clicked and the variable is set, the pipeline is in "Cancelling" state (icon could be as in running, but red)
2) when the pipeline is actually stopped (and we need to detect this somehow), it should be in "Cancelled" state

**Comment by skodapetr** [comment] 2013-09-11 18:07
Added canceled() method to context and documented in documentation. 
1) As to state "Cancelling" we are now using separate value 'stop' so I rather suggest to add new state only virtually in frontned: "Cancelling" == ("Running" + stop == true)?
2) There is already state "Cancelled" that is used by backend for pipelines that are aborted on user request.

So I suggest re-assign Bohuslav/Maria to deal with (1) and then go back to (2) or I can do it myself.

**Comment by tomas-knap** [comment] 2013-09-12 08:14
Maria, please discuss with Petr 1 and prepare that for him. Deadline tomorrow.

**Comment by tomas-knap** [comment] 2013-09-16 08:27
Petre should we test & close this issue?

**Comment by skodapetr** [comment] 2013-09-16 08:33
Nothing against testing :) But I do not know if we have DPU that use context.cancel method?

**Comment by jakubklimek** [comment] 2013-09-16 08:55
My DPUs: Ares, Buyer Profiles and PSP.CZ use canceled() as of today's morning (v0.0.3). Testing...

**Comment by jakubklimek** [comment] 2013-09-16 08:56
Anyway, you should have a testing DPU that does some dummy work to test this (cancelling, canceled, ...)

**Comment by jakubklimek** [comment] 2013-09-16 09:19
OK, it seems to be working - canceled() returns true and then my DPU deals with it, resulting in a stop.

However, since it is quick, I was unable to test the correct "Cancelling", "Canceled" sequence. Please test that using a dummy DPU that will not exit after canceled.

**Comment by jakubklimek** [comment] 2013-09-18 14:29
No one tested it even though I requested it... closing and will reopen when there is a problem.

**Comment by jakubklimek** [comment] 2013-09-24 07:09
I am almost sure that cancelling does not work as we discussed. When I click Cancel, the pipeline is immediately in the "Cancelled" state. However, it should be in "Cancelling" state until it really terminates, then "Canceled". please verify and fix if true.

**Comment by skodapetr** [comment] 2013-09-24 15:01
Still there is a problem with missing icon. Re-assign to Bohuslav. 
Bohuslav please .. we are missing icon for cancelling state in execution monitor. I can see the icon in filter but not for the execution record it self.

**Closed as completed** 2013-09-27 12:51 UTC
Labels: bug, priority:high
