### ISSUE TITLE
When connection failed, there is now way how to recover from it

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#678] opened 2013-10-18 12:48 UTC
DPU is running, rdf database is killed, DPU tries to connect again to the rdf database but is using again and again already broken conneciton, so even if the database is up and running again, the old conneciton is used again and again and the DPU cannot reconnect. 

```
2013-10-18 14:48:05,163 [Thread-15] DEBUG exec:150 dpu:108 c.c.m.x.o.r.i.VirtuosoRDFRepo - virtuoso.jdbc4.VirtuosoException: Connection failed: Broken pipe
org.openrdf.repository.RepositoryException: virtuoso.jdbc4.VirtuosoException: Connection failed: Broken pipe
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.commit(VirtuosoRepositoryConnection.java:844) ~[virtuoso-sesame-7.0.1.jar:na]
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1034) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addInputStreamToRepository(BaseRDFRepo.java:2372) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2399) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:291) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:166) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFromRDFXMLFile(BaseRDFRepo.java:192) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.intlib.extractor.simplexslt.rdfUtils.DataRDFXML.addData(DataRDFXML.java:24) [bundlefile:na]
    at cz.cuni.mff.xrg.intlib.extractor.simplexslt.SimpleXSLT.execute(SimpleXSLT.java:290) [bundlefile:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:217) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:323) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393) [backend-1.0.0.jar:na]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Broken pipe
    at virtuoso.jdbc4.VirtuosoConnection.commit(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.commit(VirtuosoRepositoryConnection.java:841) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 12 common frames omitted
2013-10-18 14:48:05,167 [Thread-15] WARN  exec:150 dpu:108 c.c.m.x.i.e.s.Simple
```

Solution: When RDFException is thrown, new connection should be tried to be established on any consequent BaseRDFRepo method call. So the method getConnection() on base rdf repo should establish new connection, if the previous end up with RDF exception.

**Comment by tomas-knap** [comment] 2013-11-22 08:53
Not working well. 

I run the pipeline with SPARQL extractor and SPARQL loader. During loading, I kill Virtuoso. Then it was trying to reconnect to Virtuoso, which is ok. But when I turn the database on, an error with Transaction occur, the execution is finished immediately, pipeline remains in the status running.  

Transaction problem: 

```
2013-11-22 09:49:19,598 [taskScheduler-2] ERROR exec: dpu: o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Transaction rolled back because transaction was set to RollbackOnly.
```

Whole log (strating with reconnects):

```
Query: ReadAllQuery(referenceClass=Schedule sql="SELECT ID, DESCRIPTION, enabled, first_exec, just_once, last_exec, NAME, time_period, period_unit, strict_tolerance, strict_timing, type, user_id, pipeline_id FROM exec_schedule WHERE (type = ?)").
2013-11-22 09:49:09,587 [taskScheduler-2] INFO  exec: dpu: o.e.p.logging.default - 2013-11-22 09:49:09.587--UnitOfWork(752818466)--Thread(Thread[taskScheduler-2,5,main])--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: SELECT ID, DESCRIPTION, enabled, first_exec, just_once, last_exec, NAME, time_period, period_unit, strict_tolerance, strict_timing, type, user_id, pipeline_id FROM exec_schedule WHERE (type = ?)
    bind => [1]
Query: ReadAllQuery(referenceClass=Schedule sql="SELECT ID, DESCRIPTION, enabled, first_exec, just_once, last_exec, NAME, time_period, period_unit, strict_tolerance, strict_timing, type, user_id, pipeline_id FROM exec_schedule WHERE (type = ?)").
2013-11-22 09:49:11,624 [taskScheduler-1] INFO  exec: dpu: o.e.p.logging.default - 2013-11-22 09:49:11.624--UnitOfWork(1533272463)--Thread(Thread[taskScheduler-1,5,main])--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (STATUS = ?)
    bind => [0]
Query: ReadAllQuery(referenceClass=PipelineExecution sql="SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (STATUS = ?)").
2013-11-22 09:49:13,969 [pool-2-thread-6] INFO  exec:176 dpu:156 o.e.p.logging.default - 2013-11-22 09:49:13.969--UnitOfWork(1363922531)--Thread(Thread[pool-2-thread-6,5,main])--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)
    bind => [176]
Query: ReadObjectQuery(name="readPipelineExecution" referenceClass=PipelineExecution sql="SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)").
2013-11-22 09:49:14,589 [taskScheduler-2] INFO  exec: dpu: o.e.p.logging.default - 2013-11-22 09:49:14.589--UnitOfWork(752818466)--Thread(Thread[taskScheduler-2,5,main])--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: SELECT ID, DESCRIPTION, enabled, first_exec, just_once, last_exec, NAME, time_period, period_unit, strict_tolerance, strict_timing, type, user_id, pipeline_id FROM exec_schedule WHERE (type = ?)
    bind => [1]
Query: ReadAllQuery(referenceClass=Schedule sql="SELECT ID, DESCRIPTION, enabled, first_exec, just_once, last_exec, NAME, time_period, period_unit, strict_tolerance, strict_timing, type, user_id, pipeline_id FROM exec_schedule WHERE (type = ?)").
2013-11-22 09:49:19,598 [taskScheduler-2] ERROR exec: dpu: o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Transaction rolled back because transaction was set to RollbackOnly.
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at cz.cuni.mff.xrg.odcs.commons.app.scheduling.ScheduleFacade$$EnhancerByCGLIB$$31703907.getAllTimeBased(<generated>) ~[cglib-3.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.scheduling.Scheduler.onTimeCheck(Scheduler.java:70) ~[backend-1.0.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_21]
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351) [na:1.7.0_21]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178) [na:1.7.0_21]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_21]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
Caused by: javax.persistence.RollbackException: Transaction rolled back because transaction was set to RollbackOnly.
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:141) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    ... 23 common frames omitted
2013-11-22 09:49:21,903 [taskScheduler-1] ERROR exec: dpu: o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Transaction rolled back because transaction was set to RollbackOnly.
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:394) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120) ~[spring-tx-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at cz.cuni.mff.xrg.odcs.commons.app.pipeline.PipelineFacade$$EnhancerByCGLIB$$553aa6e6.getAllExecutions(<generated>) ~[cglib-3.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.Engine.checkDatabase(Engine.java:120) ~[backend-1.0.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53) ~[spring-context-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_21]
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351) [na:1.7.0_21]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178) [na:1.7.0_21]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_21]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
Caused by: javax.persistence.RollbackException: Transaction rolled back because transaction was set to RollbackOnly.
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:141) ~[eclipselink-2.5.1.jar:2.5.1.v20130918-f2b9fc5]
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    ... 23 common frames omitted
2013-11-22 09:49:41,904 [taskScheduler-1] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
2013-11-22 09:49:49,599 [taskScheduler-2] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck started
2013-11-22 09:49:49,620 [taskScheduler-2] TRACE exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck finished
2013-11-22 09:50:01,906 [taskScheduler-4] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
```

**Comment by janvojt** [comment] 2013-11-28 21:06
> Not working well.
> 
> I run the pipeline with SPARQL extractor and SPARQL loader. During loading, I kill Virtuoso. Then it was trying to reconnect to Virtuoso, which is ok. But when I turn the database on, an error with Transaction occur, the execution is finished immediately, pipeline remains in the status running. 

This is not the original problem in the issue, but a duplicate of #624. It is quite clear, because issue reported a problem with RDF database (broken pipe), but this comment is talking about relational database (tx rolled back).

Please test the original problem reported (or close).

**Closed as completed** 2013-11-29 16:33 UTC
Labels: bug, priority:high, needsDiscussion, Test that
