### ISSUE TITLE
Connection failed warnings

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#600] opened 2013-10-07 12:26 UTC
It tries to reconnect two times, then ends (it should connect as many times as in config properties), further it is not clear whether finally it was connected succesfully or not. 

```
2013-10-07 14:18:40,700 [Thread-4] DEBUG exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck finished
[EL Warning]: 2013-10-07 14:19:25.762--UnitOfWork(1612025388)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
Error Code: -3
Call: SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline
Query: ReadAllQuery(referenceClass=PipelineExecution sql="SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline")
2013-10-07 14:19:25,763 [Thread-4] WARN  exec: dpu: c.c.m.x.o.b.f.PipelineFacade - Database is down after 1 attempts.
[EL Warning]: 2013-10-07 14:19:42.825--UnitOfWork(657005564)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
Error Code: -3
Call: SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline
Query: ReadAllQuery(referenceClass=PipelineExecution sql="SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline")
2013-10-07 14:19:42,826 [Thread-4] WARN  exec: dpu: c.c.m.x.o.b.f.PipelineFacade - Database is down after 2 attempts.
2013-10-07 14:19:45,581 [Thread-4] DEBUG exec: dpu: c.c.m.x.o.c.a.s.Schedule - Recieved SchedulerCheckDatabase event
```

**Comment by tomas-knap** [comment] 2013-10-07 16:01
Appears really often, now it appears just after starting backend: 

```
2013-10-07 14:29:36,417 [main] DEBUG exec: dpu: c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /data/odcs/target/lib/commons-module-1.0.0.jar
2013-10-07 14:29:36,420 [main] DEBUG exec: dpu: c.c.m.x.o.c.a.m.o.OSGIModuleFacade - Loading library: /data/odcs/target/lib/commons-module-0.0.1.jar
[EL Severe]: 2013-10-07 14:29:36.544--ServerSession(1181145092)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
Error Code: -3
[EL Severe]: ejb: 2013-10-07 14:29:36.548--ServerSession(1181145092)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
Error Code: -3
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'moduleFacade' defined in class path resource [commons-app-context.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
Error Code: -3
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
    at cz.cuni.mff.xrg.odcs.backend.AppEntry.initSpring(AppEntry.java:95)
    at cz.cuni.mff.xrg.odcs.backend.AppEntry.run(AppEntry.java:129)
    at cz.cuni.mff.xrg.odcs.backend.AppEntry.main(AppEntry.java:175)
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
Error Code: -3
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:766)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:204)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:304)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:336)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:302)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.invokeProxyMethod(AbstractEntityManagerFactoryBean.java:376)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$ManagedEntityManagerFactoryInvocationHandler.invoke(AbstractEntityManagerFactoryBean.java:517)
    at com.sun.proxy.$Proxy5.createEntityManager(Unknown Source)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:234)
    at com.sun.proxy.$Proxy13.createQuery(Unknown Source)
    at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUFacade.getAllTemplatesNoPermission(DPUFacade.java:107)
    at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUFacade$$FastClassByCGLIB$$2e8d8d2e.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
    at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUFacade$$EnhancerByCGLIB$$56c9c889.getAllTemplatesNoPermission(<generated>)
    at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.starUpLoad(OSGIModuleFacade.java:539)
    at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.start(OSGIModuleFacade.java:114)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1581)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1522)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
    ... 14 more
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
Error Code: -3
    at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316)
    at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
    at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
    at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:346)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:307)
    at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connect(DatasourceAccessor.java:434)
    at org.eclipse.persistence.sessions.server.ConnectionPool.buildConnection(ConnectionPool.java:217)
    at org.eclipse.persistence.sessions.server.ExternalConnectionPool.startUp(ExternalConnectionPool.java:146)
    at org.eclipse.persistence.sessions.server.ServerSession.connect(ServerSession.java:488)
    at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.login(DatabaseSessionImpl.java:755)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:241)
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:685)
    ... 41 more
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
    at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source)
    at virtuoso.jdbc4.Driver.connect(Unknown Source)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:187)
    at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:173)
    at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:164)
    at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:149)
    at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:119)
    at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:123)
    ... 51 more
```

**Comment by tomas-knap** [comment] 2013-10-07 16:02
Backend is falling much more often on this exception than before EclipseLink use

**Comment by tomas-knap** [comment] 2013-10-07 16:47
Yes, every second/third execution fails on this, please look on that when the issue with strange chars at the end of log messages is solved.

**Comment by tomas-knap** [comment] 2013-10-08 20:59
Napis prosim kdyz neco budes mit. Je to divne, db normalne bezi,ale spojeni se nenavaze. Nedari se mi vubec nic sebehnout, bo to vzdy spadne na tohle. Pro simulaci zkusi pustit pipelines paralelne, Jirka ted zkousel nahravat 7 milionu trojic a to bylo pry v pohode, je mozne, ze ty problemy jsou na odcs proto, ze tam ty pipeline bezi paralelne

**Comment by janvojt** [comment] 2013-10-09 07:40
I will try to reproduce tonight. Can you connect to Virtuoso with isql when this happens and issue queries?

**Comment by janvojt** [comment] 2013-10-10 17:15
I setup connection pooling, which should resolve this problem. However, quite many sockets are still  kept in TIME_WAIT state when running multiple pipelines. Please test it, problem should not occur now. I will try to research about the sockets in TIME_WAIT state.

**Comment by tomas-knap** [comment] 2013-10-13 08:05
Was testing that, the error doed not occur since that time. What about the time_wait states? Do you close the connections properly?

**Comment by janvojt** [comment] 2013-10-13 09:57
From the specification I found  about TCP, we cannot eliminate sockets in TIME_WAIT completely. I can support it with the following diagram:

![tcp_state_diagram_fixed svg](https://f.cloud.github.com/assets/2247062/1321745/944b5ca8-33e9-11e3-8972-47d61f238f85.png)

I assume we must be using "active close" connections, because we do not know in advance how much data we will send over connection, nor when we will close (connections are manage by the pool). Therefore, after we close the connection, it needs to block the port in TIME_WAIT state for the duration of timeout.

The problem is, that we have quite many connections. I am not sure if we need as many as are being open. I will consult with Petr how many threads can we expect to be spawned by backend, and therefore how many transactions can theoretically run simultaneously.

Also, the connection pool could be optimized to keep connection open for a longer period of time and possibly reuse the single connection for more transactions.

**Comment by tomas-knap** [comment] 2013-10-13 10:44
Honzo,

I would focus on reducing the number of open connections and sharing of
connections. There is no reason to have more then one connection per one
pipeline execution if the DPU are executed sequentially.

**Comment by tomas-knap** [comment] 2013-10-14 10:50
Do you provide configurable number of connections (in config.properties) available in the pool? THen we can close this

**Comment by janvojt** [comment] 2013-10-17 07:11
This is resolved by using connection pools for RDF, relational data and logback.

It would be possible to configure the following parameters, however I do not think it would help anything. Pool size is adjusted dynamically according to current needs. Tampering with the pool settings can bring new problems. It would be too complicated for user to set. We would need in total 3 configurations, because we use 3 different instances of connection pools.

```
initialSize = 0
maxActive = 8
maxIdle = 8
maxOpenPreparedStatements = -1
maxWait = -1
minEvictableIdleTimeMillis = 1800000
minIdle = 0
numTestsPerEvictionRun = 3
```

I am closing this, if you have further problems with big number of connections, reopen. If you insist on configuring connection pools from config file, also reopen.

**Closed as completed by janvojt** 2013-10-17 07:11 UTC
Labels: bug, priority:high

**Comment by tomas-knap** [comment] 2013-10-17 07:17
Ok, just please comment all these params
