### ISSUE TITLE
EclipseLink has problems when the pipeline is about to finishWhen debugging DPU the status in exec monitor remains "running"

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#594] opened 2013-10-06 13:40 UTC
Two times it happened to me that all DPUs were run, finished successfully, but the end of the execution was: 

![screen shot 2013-10-06 at 6 02 45 pm](https://f.cloud.github.com/assets/3014917/1276957/edca6fec-2ea0-11e3-9555-97270cd22d86.png)

As a result, the execution ends immediately, the status of the executed pipeline remains "running". DB is up and running

**Comment by tomas-knap** [comment] 2013-10-07 09:07
relates to #561

**Comment by janvojt** [comment] 2013-10-12 18:07
This is a duplicate of #600, I am closing this.

**Closed as completed by janvojt** 2013-10-12 18:07 UTC
Labels: bug, duplicate, priority:high
