### ISSUE TITLE
Connection refused and as a result the pipeline exucution fall down, pipeline remains in status running!

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#611] opened 2013-10-10 12:26 UTC
End of execution Log is below, it was pipeline execution: 10111, on odcs.xrg.cz, pipeline "Decisions from nsoud, with the first DPU configured as:

![screen shot 2013-10-10 at 2 25 23 pm](https://f.cloud.github.com/assets/3014917/1306021/134fc7fe-31a7-11e3-91eb-59153a70c3ad.png)

There was no pipeline running in paralel.

```
2013-10-10 10:31:05,100 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.i.e.l.d.j.JTagger - /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/jtagger/final.xml
2013-10-10 10:31:05,101 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.i.e.l.d.j.JTagger - /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/jtagger/final.html
2013-10-10 10:31:05,101 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.i.e.l.d.JTaggerAnnotator - File /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/outJTagger/938.xml was generated as result of URI generator
2013-10-10 10:31:05,101 [Thread-143] INFO  exec:10111 dpu:9 c.c.m.x.i.e.l.d.JTaggerAnnotator - Jtagger annotator finished successfully
2013-10-10 11:20:37,825 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.o.c.m.u.DataUnitUtils - Dir /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/outMetaElem/ NOT created, could have already exist
2013-10-10 11:20:37,829 [Thread-143] INFO  exec:10111 dpu:9 c.c.m.x.i.e.l.d.JTaggerAnnotator - Not found label: Důvod dovolání : 
2013-10-10 11:20:37,831 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.i.e.l.d.JTaggerAnnotator - File /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/outMetaElem/938.xml was generated as result of URI generator
2013-10-10 11:20:37,831 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.i.e.l.d.JTaggerAnnotator - About add paragraphs elements
2013-10-10 11:20:37,831 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.o.c.m.u.DataUnitUtils - Dir /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/outURIGenPara NOT created, could have already exist
2013-10-10 11:20:37,832 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.i.e.l.d.JTaggerAnnotator - File /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/outURIGenPara/938.xml was generated as result of URI generator
2013-10-10 11:20:37,832 [Thread-143] INFO  exec:10111 dpu:9 c.c.m.x.i.e.l.d.JTaggerAnnotator - Metadata and paragraph elements generated, about to create output
2013-10-10 11:20:37,833 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.o.c.m.u.DataUnitUtils - Dir /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/out NOT created, could have already exist
2013-10-10 11:20:37,833 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.o.c.m.u.DataUnitUtils - File path /data/odcs/backend/working/10111/working/dpu_9_legislation-dec-jTaggerAnnotator/tmp/out/938.ttl
Connection to jdbc:virtuoso://localhost:1119/charset=UTF-8/log_enable=2 is FAILED.
2013-10-10 11:20:37,835 [Thread-143] DEBUG exec:10111 dpu:9 c.c.m.x.o.r.i.VirtuosoRDFRepo - virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
org.openrdf.repository.RepositoryException: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
    at virtuoso.sesame2.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:231) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.FailureTolerantRepositoryWrapper.getConnection(FailureTolerantRepositoryWrapper.java:113) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2417) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:285) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:160) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFromTurtleFile(BaseRDFRepo.java:174) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.intlib.extractor.legislation.decisions.JTaggerAnnotator.execute(JTaggerAnnotator.java:223) [bundlefile:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:217) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:323) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393) [backend-1.0.0.jar:na]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.Driver.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_40]
    at java.sql.DriverManager.getConnection(DriverManager.java:215) ~[na:1.7.0_40]
    at virtuoso.sesame2.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:226) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 10 common frames omitted
2013-10-10 11:20:37,837 [Thread-143] ERROR exec:10111 dpu:9 c.c.m.x.o.b.dpu.event.DPUEvent - Failed to create DataUnit for DPU 'legislation-dec-jTaggerAnnotator'
cz.cuni.mff.xrg.odcs.rdf.exceptions.RDFException: Error by adding file to repository virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2443) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:285) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:160) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFromTurtleFile(BaseRDFRepo.java:174) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.intlib.extractor.legislation.decisions.JTaggerAnnotator.execute(JTaggerAnnotator.java:223) ~[na:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:217) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:323) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393) [backend-1.0.0.jar:na]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: org.openrdf.repository.RepositoryException: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
    at virtuoso.sesame2.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:231) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.FailureTolerantRepositoryWrapper.getConnection(FailureTolerantRepositoryWrapper.java:113) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2417) ~[RDF-1.0.0.jar:na]
    ... 8 common frames omitted
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.Driver.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_40]
    at java.sql.DriverManager.getConnection(DriverManager.java:215) ~[na:1.7.0_40]
    at virtuoso.sesame2.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:226) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 10 common frames omitted
[EL Warning]: 2013-10-10 11:20:52.832--UnitOfWork(711218497)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (context_id = ?)
    bind => [1 parameter bound]
Query: ReadObjectQuery(name="execution" referenceClass=PipelineExecution sql="SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (context_id = ?)")
[EL Warning]: 2013-10-10 11:20:52.832--UnitOfWork(474342730)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)
    bind => [1 parameter bound]
Query: ReadObjectQuery(name="readPipelineExecution" referenceClass=PipelineExecution sql="SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)")
Exception in thread "pool-2-thread-17" Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)
    bind => [1 parameter bound]
Query: ReadObjectQuery(name="readPipelineExecution" referenceClass=PipelineExecution sql="SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (ID = ?)")
    at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316)
    at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
    at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
    at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:346)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:307)
    at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.reconnect(DatasourceAccessor.java:581)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.reconnect(DatabaseAccessor.java:1625)
    at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.incrementCallCount(DatasourceAccessor.java:321)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:613)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991)
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:250)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectOneRow(DatasourceCallQueryMechanism.java:714)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRowFromTable(ExpressionQueryMechanism.java:2800)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRow(ExpressionQueryMechanism.java:2753)
    at org.eclipse.persistence.queries.ReadObjectQuery.executeObjectLevelReadQuery(ReadObjectQuery.java:545)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1168)
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1127)
    at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:431)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1215)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793)
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863)
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5529)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829)
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863)
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5529)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829)
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863)
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5529)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829)
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863)
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.retryQuery(UnitOfWorkImpl.java:5529)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1726)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.executeQuery(EntityManagerImpl.java:900)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.findInternal(EntityManagerImpl.java:843)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:719)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:588)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:365)
    at com.sun.proxy.$Proxy14.find(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
    at com.sun.proxy.$Proxy13.find(Unknown Source)
    at cz.cuni.mff.xrg.odcs.commons.app.pipeline.PipelineFacade.getExecution(PipelineFacade.java:205)
    at cz.cuni.mff.xrg.odcs.backend.facade.PipelineFacade.getExecution(PipelineFacade.java:107)
    at cz.cuni.mff.xrg.odcs.backend.facade.PipelineFacade$$FastClassByCGLIB$$4ce56639.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
    at cz.cuni.mff.xrg.odcs.backend.facade.PipelineFacade$$EnhancerByCGLIB$$28a2feeb.getExecution(<generated>)
    at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.execute(Executor.java:346)
    at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.run(Executor.java:431)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
    at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source)
    at virtuoso.jdbc4.Driver.connect(Unknown Source)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:187)
    at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:173)
    at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:164)
    at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:149)
    at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:119)
    at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:123)
    ... 67 more
[EL Warning]: 2013-10-10 11:20:52.841--ClientSession(432599954)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: select sequence_next('seq_exec_record')
Query: ValueReadQuery(sql="select sequence_next('seq_exec_record')")
Exception in thread "Thread-143" Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
Error Code: -3
Call: select sequence_next('seq_exec_record')
Query: ValueReadQuery(sql="select sequence_next('seq_exec_record')")
    at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316)
    at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
    at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
    at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:346)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:307)
    at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.reconnect(DatasourceAccessor.java:581)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.reconnect(DatabaseAccessor.java:1625)
    at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.incrementCallCount(DatasourceAccessor.java:321)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:613)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991)
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
    at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:250)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelect(DatasourceCallQueryMechanism.java:281)
    at org.eclipse.persistence.queries.DataReadQuery.executeNonCursor(DataReadQuery.java:197)
    at org.eclipse.persistence.queries.DataReadQuery.executeDatabaseQuery(DataReadQuery.java:152)
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
    at org.eclipse.persistence.queries.DataReadQuery.execute(DataReadQuery.java:137)
    at org.eclipse.persistence.internal.sessions.AbstractSession.internalExecuteQuery(AbstractSession.java:3203)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793)
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863)
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829)
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863)
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829)
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863)
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829)
    at org.eclipse.persistence.internal.sessions.AbstractSession.retryQuery(AbstractSession.java:1863)
    at org.eclipse.persistence.sessions.server.ClientSession.retryQuery(ClientSession.java:687)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1829)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1726)
    at org.eclipse.persistence.sequencing.QuerySequence.select(QuerySequence.java:309)
    at org.eclipse.persistence.sequencing.QuerySequence.updateAndSelectSequence(QuerySequence.java:254)
    at org.eclipse.persistence.sequencing.StandardSequence.getGeneratedVector(StandardSequence.java:71)
    at org.eclipse.persistence.sequencing.Sequence.getGeneratedVector(Sequence.java:257)
    at org.eclipse.persistence.internal.sequencing.SequencingManager$Preallocation_NoTransaction_State.getNextValue(SequencingManager.java:664)
    at org.eclipse.persistence.internal.sequencing.SequencingManager.getNextValue(SequencingManager.java:1067)
    at org.eclipse.persistence.internal.sequencing.ClientSessionSequencing.getNextValue(ClientSessionSequencing.java:70)
    at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:361)
    at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:320)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.assignSequenceNumber(UnitOfWorkImpl.java:486)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNotRegisteredNewObjectForPersist(UnitOfWorkImpl.java:4281)
    at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.registerNotRegisteredNewObjectForPersist(RepeatableWriteUnitOfWork.java:518)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNewObjectForPersist(UnitOfWorkImpl.java:4226)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.persist(EntityManagerImpl.java:496)
    at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
    at com.sun.proxy.$Proxy13.persist(Unknown Source)
    at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUFacade.save(DPUFacade.java:368)
    at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUFacade$$FastClassByCGLIB$$2e8d8d2e.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
    at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUFacade$$EnhancerByCGLIB$$685fd272.save(<generated>)
    at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onDPUEvent(EventListenerDatabase.java:29)
    at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onApplicationEvent(EventListenerDatabase.java:45)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:223)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:323)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393)
    at java.lang.Thread.run(Thread.java:724)
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
    at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source)
    at virtuoso.jdbc4.Driver.connect(Unknown Source)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:187)
    at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:173)
    at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:164)
    at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:149)
    at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:119)
    at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:123)
    ... 71 more
2013-10-10 11:20:58,317 [Thread-4] DEBUG exec: dpu: c.c.m.x.o.c.a.s.Schedule - Recieved SchedulerCheckDatabase event
2013-10-10 11:20:58,317 [Thread-4] DEBUG exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck started
2013-10-10 11:20:58,487 [Thread-4] DEBUG exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck finished
```

**Comment by janvojt** [comment] 2013-10-12 18:05
This looks like a duplicate of #600, which should already be resolved by connection pooling in commit 54a10a3. I am closing this.

**Closed as completed by janvojt** 2013-10-12 18:05 UTC
Labels: bug, duplicate, priority:urgent
