### ISSUE TITLE
DPUs distribution on canvas

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#65] opened 2013-07-01 14:42 UTC
When I create some pipeline, save it I will go back, my DPUs have different layout than the origin. 

DPUs are not at the same place - they are minimal distance to each other.

**Comment by bogo777** [comment] 2013-07-01 16:18
It was caused by saving unnormalized coordinates. DPU coordinate was dependent on zoom. Fixed by saving normalized coordinates only.

**Closed as completed by bogo777** 2013-07-01 16:18 UTC
Labels: bug, priority:normal
