### ISSUE TITLE
Problem connecting to DB appears although config.properties is set to infinite #tries

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#605] opened 2013-10-09 12:19 UTC
When running jTaggerPipeline, it fails when creating output for uriGenerator and finished. 

Correct behaviour: It should try to reconnect and should not continue further

Reassign to Jirka, if applicable.

2013-10-09 13:48:08,968 [Thread-11] INFO  exec:10094 dpu:8 c.c.m.x.i.e.l.d.UriGenerator - URI generator successfully executed, creating output
2013-10-09 13:48:08,975 [Thread-11] DEBUG exec:10094 dpu:8 c.c.m.x.o.c.m.u.DataUnitUtils - Dir /data/odcs/backend/working/10094/working/dpu_8_legislation-dec-uriGenerator/tmp/out NOT created, could have already exist
2013-10-09 13:48:08,976 [Thread-11] DEBUG exec:10094 dpu:8 c.c.m.x.o.c.m.u.DataUnitUtils - File path /data/odcs/backend/working/10094/working/dpu_8_legislation-dec-uriGenerator/tmp/out/139.ttl
Connection to jdbc:virtuoso://localhost:1119/charset=UTF-8/log_enable=2 is FAILED.
2013-10-09 13:48:08,990 [Thread-11] DEBUG exec:10094 dpu:8 c.c.m.x.o.r.i.VirtuosoRDFRepo - virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
org.openrdf.repository.RepositoryException: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
    at virtuoso.sesame2.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:231) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.FailureTolerantRepositoryWrapper.getConnection(FailureTolerantRepositoryWrapper.java:113) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2417) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:285) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:160) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFromTurtleFile(BaseRDFRepo.java:174) [RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.intlib.extractor.legislation.decisions.UriGenerator.execute(UriGenerator.java:173) [bundlefile:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:217) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:323) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393) [backend-1.0.0.jar:na]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.Driver.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_40]
    at java.sql.DriverManager.getConnection(DriverManager.java:215) ~[na:1.7.0_40]
    at virtuoso.sesame2.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:226) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 10 common frames omitted
2013-10-09 13:48:08,992 [Thread-11] ERROR exec:10094 dpu:8 c.c.m.x.o.b.dpu.event.DPUEvent - Failed to create DataUnit for DPU 'legislation-dec-uriGenerator'
cz.cuni.mff.xrg.odcs.rdf.exceptions.RDFException: Error by adding file to repository virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2443) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:285) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:160) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFromTurtleFile(BaseRDFRepo.java:174) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.intlib.extractor.legislation.decisions.UriGenerator.execute(UriGenerator.java:173) ~[na:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:217) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:323) [backend-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:393) [backend-1.0.0.jar:na]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: org.openrdf.repository.RepositoryException: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
    at virtuoso.sesame2.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:231) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.FailureTolerantRepositoryWrapper.getConnection(FailureTolerantRepositoryWrapper.java:113) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:2417) ~[RDF-1.0.0.jar:na]
    ... 8 common frames omitted
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.jdbc4.Driver.connect(Unknown Source) ~[jdbc-driver-4.jar:na]
    at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_40]
    at java.sql.DriverManager.getConnection(DriverManager.java:215) ~[na:1.7.0_40]
    at virtuoso.sesame2.driver.VirtuosoRepository.getConnection(VirtuosoRepository.java:226) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 10 common frames omitted
2013-10-09 13:48:13,309 [Thread-4] DEBUG exec: dpu: c.c.m.x.o.c.a.s.Schedule - Recieved SchedulerCheckDatabase event
2013-10-09 13:48:13,309 [Thread-4] DEBUG exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck started
2013-10-09 13:48:13,494 [Thread-4] DEBUG exec: dpu: c.c.m.x.o.c.a.s.Schedule - onTimeCheck finished
2013-10-09 13:48:14,121 [Thread-11] INFO  exec:10094 dpu:8 c.c.m.x.o.b.dpu.event.DPUEvent - DPU 'legislation-dec-uriGenerator' finished
2013-10-09 13:48:14,575 [pool-2-thread-1] DEBUG exec:10094 dpu:8 c.c.m.x.o.b.e.p.impl.CleanUp - CleanUp start ..

**Comment by tomas-knap** [comment] 2013-10-09 12:52
And strange is that there is exception:  "Error by adding file to repository virtuoso.jdbc4.VirtuosoException: Connection failed: Cannot assign requested address", but I would expect version jdbc3?

**Comment by janvojt** [comment] 2013-10-12 18:09
Duplicate of #600, I am closing this.

**Closed as completed by janvojt** 2013-10-12 18:09 UTC
Labels: bug, duplicate, priority:high
